### ISSUE TITLE
SoundCloud audio skipping

### ISSUE THREAD

**Issue by AbsoluteVendingMachine** [futo-org/grayjay-android#1089]
Whenever listening to something on SoundCloud it skips / fast forwards a little bit after 1 or 2 seconds from the beginning every time.

Device: Samsung Galaxy S24+

**Comment by codebymatter** [comment]
Thia is an issie that has been present with SoundCloud since Grayjay went live to public. Cannot say what is causing the issue to prevail but it happens when you replay the song or "video" over again or adjust the track finder only for SoundCloud to produce an error.

With Spotify in the list of plugins, it may be a new option to consider. It is buggy when fcasting but works without. I do hope SoundCloud bug is resolved someday.

**Comment by kaidelorenzo** [comment]
We're having trouble reproducing this issue. Could you verify that the issue still exists and add some additional details about how to reproduce it and what exactly is going wrong?
