### ISSUE TITLE
Polycentric comments do not Show Up

### ISSUE THREAD

**Issue by silvaf6** [futo-org/grayjay-android#1281]
### What happened?

I think it happent after purchasing the app and putting on my license.

I might have clicked "I've already paid" a while ago, but always had the intent to purchase it to support rossman futo team and show a certain finger to google.

Only waited for some backup money, purchased it, aswell futo keyboard and the voice transcript.

So i am not on bad faith, only trying to be honest for you to see if that was the cause of the issue.

Sorry about that.

I read the FAQ page, supposelly someone/ something is on the their own to block them.

I'm just not sure if that is the case or a bug.

I do not insult anyone, i might swear, but i think that is the point of running from googles grasp.

Or did i write a comment of three parts, and it was marked as spam?

I'm just trying to engage the grayjay community, even on videos someone might only read in about a year, while expressing my educated opinions, or just humor without "racism" or stuff like that, dependig on the type of video.

I sure do hope rossman keeps promoting it so we can support the devs and promote a bit of "free internet" barebones concept. Probably you will need to charge again.

I am all with pay once for life, but android and youtube api updates, surely will require more resources and you might ran out of budget. But i am sure everything is being tought about it.

I might only talk ** about big tech companies, not good honest youtubers.

Not sure what to mark as "plugin", only use the youtube functionality, and i stay the heck away from the irrelevant youtube alhorithm " trending tab" (home), there is nothing for me there, only bad promoted quality content.

You might want to pinpoint us more about the "polycentric" in case of some simple AI is flagging comments and its terms to reputation comments.

thanks!

### Grayjay Version

253

### What plugins are you seeing the problem on?

Other

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by TheQuickFox** [comment]
Join the club:
https://github.com/futo-org/grayjay-android/issues/1074
https://github.com/futo-org/grayjay-android/issues/1113
https://github.com/futo-org/grayjay-android/issues/1149
https://github.com/futo-org/grayjay-android/issues/1171
https://github.com/futo-org/grayjay-android/issues/1202

Unfortunately, GrayJay support seems to be non-existent. So move on to another app like NewPipe or ReVanced.

**Comment by b-risk** [comment]
> Join the club: #1074 #1113 #1149 #1171 #1202
> 
> Unfortunately, GrayJay support seems to be non-existent. So move on to another app like NewPipe or ReVanced.

FUTO is active on their Zulip (chat.futo.org), plus they are working hard to get the Desktop application out and trying to bypass whatever YT is doing to break the app.

**Comment by codebymatter** [comment]
> > Join the club: #1074 #1113 #1149 #1171 #1202
> > Unfortunately, GrayJay support seems to be non-existent. So move on to another app like NewPipe or ReVanced.
> 
> FUTO is active on their Zulip (chat.futo.org), plus they are working hard to get the Desktop application out and trying to bypass whatever YT is doing to break the app.

I agree this is the case alright. Grayjay is already set to turn 1 year since its launch last year and back then we only had about 4 addons and two of which were in Beta state. It has evolved since. If Ibhad tobrate it's current state eight now it would sit on 70%. It is functional, a few bugs here and there but it works. I bought two licenses and don't regret it at all.

**Comment by usertoroot** [comment]
The Polycentric comments not showing is not something that is in our control. We communicated this to the relevant team. For now on the Grayjay team we've decided to make platform comments the default (for new users) so it causes less confusion. That is the way it is for now...

On the Grayjay side we released quite a few updates today and hope to solve many more bugs soon. Desktop app is already in internal alpha.

**Comment by codebymatter** [comment]
I'm taking chance tobask a question. I've noticed in the patch notes that Polycentric profiles are linked to Harbor.

In the Polycentric Wiki, one of the suggested steps when creating Polycentric is to use Harbor to link our Polycentric account with our creator accounts. I had always thought that suggestion was meant only for Content Creators so I skipped it.

Could not having linked profile to Harbor be the cause of bugs relating to comments and possibly even functionality on Polycentric webapp?

**Comment by I-I-IT** [comment]
I personally never have problem, and never had. Graphene Pixel 9, previously stock Galaxy device.

**Comment by Assblastois** [comment]
I still have this problem. It started 3 months ago or so. I would love to actually interact with other people on the app.

**Comment by mathix420** [comment]
It happened again for me, I think I have more insight to possibly find the source of the issue.

1. Post a comment on a video
2. Delete this comment
3. Post again on the same video

And suddenly none of your comments are being published...

**Comment by mathix420** [comment]
I've found a fix https://github.com/futo-org/grayjay-android/issues/1074#issuecomment-2352175180

**Comment by TheQuickFox** [comment]
> I've found a fix [#1074 (comment)](https://github.com/futo-org/grayjay-android/issues/1074#issuecomment-2352175180)

Thanks. This fixes the issue. So I guess it was a GrayJay problem after all.

**Comment by Assblastois** [comment]
I just made a new profile and it works now. Trying to copy and save my polycentric link to follow the steps linked by @mathix420 fucked something up, and trying to paste it would lag out my phone, to a point where I thought it would crash the whole device. The link was so long that my note app couldn't handle it.

**Comment by TheQuickFox** [comment]
> I just made a new profile and it works now. Trying to copy and save my polycentric link to follow the steps linked by @mathix420 fucked something up, and trying to paste it would lag out my phone, to a point where I thought it would crash the whole device. The link was so long that my note app couldn't handle it.

Yeah the whole Polycentric identity should become an export to a file instead of a huge text link to the clipboard because it is getting way too long. The application freezes and there is the risk of corruption of the text string while transferring it. Just make it a .zip file or something.
