### ISSUE TITLE
Videos stops playback after 1min in YouTube, and no playback at all in Spotify

### ISSUE THREAD

**Issue by SovietGP** [futo-org/grayjay-android#1610]
### What happened?

Both Spotify and YouTube have playback problems, YouTube stops playing any video after 1min and won't play any more. Spotify doesn't play at all, all I see is a white play button that I can't press, the plugin hasn't worked since it was first implemented. I have tried reinstalling the plugins, reinstalling Grayjay, tried messing with the webm loading settings for audio and video, nothing seems to work or make a difference. I'm using the latest version of MulchWebview and on sdk 29 if that helps, it's using the default config. Also age restricted content fallsbavk to UMP and freezes after 1min, I tried forcing webm but nothing changes, seems like Grayjay doesn't like my YouTube or Spotify even though they both work independently in any browser I use and both work fine on their own, I'm using Revanced for now, there is no issues there at all. 

### Grayjay Version

276

### What plugins are you seeing the problem on?

Youtube, Other

### Plugin Version

YouTube (219) Spotify (12)

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by SovietGP** [comment]
Update: did some reinstalling of YouTube and managed to get IOS playback on a few videos, a lot of my videos and subscriptions are age restricted by youtube, I am unable to play anything for over 1min and Spotify just doesn't work for any at all nothing works.

**Comment by SovietGP** [comment]
> Just to confirm, sorry I asked this already in another thread, you are not using VPN?

I use adaway and I disabled the hosts file before trying, no other VPN is used. The problem occurrs regardless of the settings.

**Comment by SovietGP** [comment]
> Had the same issue today, but solved after disconnecting and reconnecting from my VPN (ProtonVPN).
> 
> I was connected to Belgium since Dec 7 due to travelling, and it was still in that location. When reconnecting to my regular country, it started working again. Is it possible it's some kind of geolocation issue/restriction?
> 
> I know for sure Spotify blocks their app if you're abroad for too long (happened to me once), which seems to line up with Spotify not playing at all.

don't use VPN's only host file blocking.

**Comment by Zvonimir-FUTO** [comment]
> Had the same issue today, but solved after disconnecting and reconnecting from my VPN (ProtonVPN).
> 
> I was connected to Belgium since Dec 7 due to travelling, and it was still in that location. When reconnecting to my regular country, it started working again. Is it possible it's some kind of geolocation issue/restriction?
> 
> I know for sure Spotify blocks their app if you're abroad for too long (happened to me once), which seems to line up with Spotify not playing at all.

It appears Youtube throttles VPN activity although the reason is not familiar to me but if I could guess it is probably based on geolocation.

**Comment by Zvonimir-FUTO** [comment]
> > > Had the same issue today, but solved after disconnecting and reconnecting from my VPN (ProtonVPN).
> > > I was connected to Belgium since Dec 7 due to travelling, and it was still in that location. When reconnecting to my regular country, it started working again. Is it possible it's some kind of geolocation issue/restriction?
> > > I know for sure Spotify blocks their app if you're abroad for too long (happened to me once), which seems to line up with Spotify not playing at all.
> > 
> > 
> > It appears Youtube throttles VPN activity although the reason is not familiar to me but if I could guess it is probably based on geolocation.
> 
> Are you saying that due to my geographic position in the world, which is western Europe, that I am unable to use Grayjay to watch YouTube and listen to Spotify. That sounds quite ridiculous if I may. I don't use VPNs which makes this all the more strange.

No. You can clearly see that I was quoting and responding to @ThePrivacyPlayer.

**Comment by SovietGP** [comment]
> > > > Had the same issue today, but solved after disconnecting and reconnecting from my VPN (ProtonVPN).
> > > > I was connected to Belgium since Dec 7 due to travelling, and it was still in that location. When reconnecting to my regular country, it started working again. Is it possible it's some kind of geolocation issue/restriction?
> > > > I know for sure Spotify blocks their app if you're abroad for too long (happened to me once), which seems to line up with Spotify not playing at all.
> > > 
> > > 
> > > It appears Youtube throttles VPN activity although the reason is not familiar to me but if I could guess it is probably based on geolocation.
> > 
> > 
> > Are you saying that due to my geographic position in the world, which is western Europe, that I am unable to use Grayjay to watch YouTube and listen to Spotify. That sounds quite ridiculous if I may. I don't use VPNs which makes this all the more strange.
> 
> No. You can clearly see that I was quoting and responding to @ThePrivacyPlayer.

I am aware, I was merely presuming that due to location and maybe the way Grayjay handles the requests that my location data was incorrect somehow.

**Comment by SovietGP** [comment]
@Zvonimir-FUTO I uave tried this setting already it doesn't seem to do anything, the videos still have the same issue.

**Comment by SovietGP** [comment]
@ThePrivacyPlayer I have tried disabling adaway and it didn't make any difference, I don't think adaway is the culprit here.

**Comment by make-suffer** [comment]
> > Had the same issue today, but solved after disconnecting and reconnecting from my VPN (ProtonVPN).
> > 
> > I was connected to Belgium since Dec 7 due to travelling, and it was still in that location. When reconnecting to my regular country, it started working again. Is it possible it's some kind of geolocation issue/restriction?
> > 
> > I know for sure Spotify blocks their app if you're abroad for too long (happened to me once), which seems to line up with Spotify not playing at all.
> 
> don't use VPN's only host file blocking. 

And what if I cannot access youtube without VPN? The official app works fine though.

**Comment by KrareophKhesheare** [comment]
Yeah, same here. Hard stop at 0:59. A few reinstalls with different versions (unversal, v8a [Pixel 8 Pro]), installing the new from today (ongoing problem 2+ weeks), removing cached versions, reinstalling yt-plugin... Nothing works. Or rather, in between, I got negative playtimes [0:00 / -12:-55].
Basically unusable at this point in time.

**Comment by kuligs2** [comment]
> Yeah, same here. Hard stop at 0:59. A few reinstalls with different versions ( universal, v8a [Pixel 8 Pro, Stock Android 15, Build AP4A.241205.013]). Installing the new version from today (v278, ongoing problem 2+ weeks), removing cached versions, reinstalling yt-plugin (v219... Nothing works. Or rather, in between, I got negative playtimes [0:00 / -12:-55]. Basically unusable at this point in time. And queued downloads instantly crashing.

Sir, are you logged into your youtube account when this happens?

If the answer is yes, its most likely the newest sanction package rolling out against the adblockers. I too experienced this on my daily driver web browser. For years i was blocking ads with no problems then one day few weeks ago, yt started blocking me from watching. It even cached my clearnet rig somehow, and even logging out i cant watch videos.. THey stop after 0:59, and wont load anymore. I cant skip videos.. yt just blocks my cookie along with (tried to refresh browser and private window) but to no avail.. 

Freetube works, newpipe works.. i dont use gray jay because they dont have desktop app that works with either freetube and newpipe substription exports.

**Comment by Mr-Savag3** [comment]
Also having this issue, only on certain videos (usually videos under 3 minutes long). Experimental UMP is on, no VPN being used, living in the Continental USA, logged in to YouTube. The video also won't download if I try. 
The video player acts like I clicked pause, but won't let me click play again.

**Comment by finnigan82** [comment]
I also have this exact same issue. Video content doesn't load further than 1 minute on any YouTube video.

Also tried everything the other users have mentioned above. 

Using Android app version 278 on Android 15

**Comment by bman1907** [comment]
For me, this problem only occurred when using UMP. I had the problem only sometimes happen, and it was always when using data. When on data, it sometimes fails to load IOS stream data and used UMP instead. When I turned on Force UMP, every video froze at 1:00, no matter my network. I live in Southeastern US and don't use a VPN.

**Comment by kuligs2** [comment]
resolved!
Either ublockorigin blocks the domain: jnn-pa.googleapis.com or something else.
I run pihole, and at first glance didnt see any google/youtube domains being blocked but i found a reddit post that mentioned this to be unblocked.. I whitelsited and now everything works.

**Comment by Zvonimir-FUTO** [comment]
Unfortunately that isn't it. We found the cause of the playback issues on certain IPs.
The conclusion is that UMP in general now mandates PO tokens (Proof of Origin token).
This is a complex sandboxed algorithm that generates an identifying token based on your browser environment. We are working on fixing this but it will take time. In the meantime, UMP is broken. We will notify you as soon as it is fixed.

**Comment by Shakool** [comment]
In case that helps, also have the same issue while Proton VPN is active. However I found that after trying several times the videos is allowed to play. Basically, it block and reset ~5times then Grayjay ask to reload the YouTube plug-in, I click yes and ~2-3 times later the video can play.

**Comment by Mr-Savag3** [comment]
Yeah it's definitely still an issue, not resolved. Hopefully it can be fixed soon. A lot of videos work with UMP turned off, but many still don't.

**Comment by grappas** [comment]
I noticed that the issue does not occur on my home WiFi (but it does occur on mobile data). So, I set up OpenVPN on the server. Unfortunately, the issue persisted.

**Comment by easter-eat-ser** [comment]
Issue continues, for me this issue has appeared alongside Grayjay saying 'Failed to get iOS stream data, fallback to UMP'

**Comment by easter-eat-ser** [comment]
(No VPN, live in Canada)

**Comment by charliefrance** [comment]
Same here, 'Failed to get iOS stream data, fallback to UMP'. Only happens on WiFi, not on mobile data

**Comment by Zvonimir-FUTO** [comment]
Hi everyone, this has been finally fixed and new version of Grayjay and Youtube have been released!

Go update and test and tell us if you find issues except the one below.

We are aware that age restricted, controversial videos, or other videos that require login may not yet work. We will be working on this next week.

The desktop release that is required for this fix will also be released next week.

**Comment by charliefrance** [comment]
This has fixed it! As far as I can tell, works with VPN and on WiFi and Mobile Data

**Comment by ThePrivacyPlayer** [comment]
@Zvonimir-FUTO This is still happening for me unfortunately (I'm on version 281, is this the latest one?).

Whenever the stream defaults to UMP (which is all the time for me, even though I disabled "Force UMP" option), the video still stops after 1min.

Is there anything I need to check in the configuration?

**Comment by Some-Noob** [comment]
New user here. I tried Grayjay for the first time and am experiencing the same issues with others in the thread. YT videos don't play. The ones that do play don't go past 1 minute. I get negative play times (exactly 0:00 / -12:-55). It happens on the play store version so I downloaded the official apk from the website. It's the same on both.

Version 281
Samsung Galaxy A12

**Comment by grappas** [comment]
Fix works for me. Two details though:
- cannot switch to background playback
- my network traffic goes through pihole

**Comment by osimarr** [comment]
This still happens to me.
Grayjay 281, youtube 221

**Comment by jmcgaughey** [comment]
still not for me either the mp4 vids play fine but webm forget it after 1 min

**Comment by tealtxgr** [comment]
> still not for me either the mp4 vids play fine but webm forget it after 1 min
> 
> grayjay version 281 yt version 221

Sad to report I'm still having the same issue. I did actually check and yeah this seems to only affect UMP streams.

**Comment by Mr-Savag3** [comment]
Still happens for me as well. Sometimes reloading the video works, but other times it freezes at 1min, or worse, now I have an issue where the entire video won't load, or the app may even crash. 

The problem is almost worse.

**Comment by jmcgaughey** [comment]
> Still happens for me as well. Sometimes reloading the video works, but other times it freezes at 1min, or worse, now I have an issue where the entire video won't load, or the app may even crash.
> 
> The problem is almost worse.

/

**Comment by jmcgaughey** [comment]
same problem even after the 281 update but just seems to be on the webm vids idk if thats an issue w the plugin for yt or the app itself. this was never an issue before, probably about a week or more its been doing this

**Comment by Mr-Savag3** [comment]
I need to close and re-open each video multiple times now, or it simply won't play. The Grayjay app is now worse.

**Comment by easter-eat-ser** [comment]
Fix did absolutely nothing. Either fix UMP playback or IOS playback, but Grayjay Youtube is basically unusable

**Comment by ThePrivacyPlayer** [comment]
> > Fix did absolutely nothing. Either fix UMP playback or IOS playback, but Grayjay Youtube is basically unusable
> 
> They've already stated that they're working on it. What is this comment supposed to achieve?

They closed this issue 3 days ago and marked it as completed, saying that a fix was live in the latest release. However, the fix clearly did not work for many people, so we're asking that they reopen the issue.

**Comment by tealtxgr** [comment]
Wow, the insane entitlement in some of these latest replies...

**Comment by tealtxgr** [comment]
The fact that you bring up donators leads me to believe you are not one and are just using it to strengthen your argument. Kinda like how people love to speak for the disabled to get what the want. 

Oh well. I'm only gonna respond if it's information that will help FUTO. 

Best of luck team ✌️

**Comment by jmcgaughey** [comment]
that fact that my point blew over your tiny head is sad...if your looking for an argument head over to facebook or reddit. have a good day little buddy

**Comment by jmcgaughey** [comment]
im out of here...too toxic

**Comment by Zvonimir-FUTO** [comment]
Hey guys there is no need for any tensions or arguing. Issue is not being forgotten. I just closed it when it was fixed and got to these comments just now (after reading hundreds of others on other issues) and seeing you guys are reporting here still.

For easier tracking we won't reopen this one since we already have these three opened: #1807 #1639 #1596 and it is already hard to track everything through those 3.

> Fix did absolutely nothing. Either fix UMP playback or IOS playback, but Grayjay Youtube is basically unusable
@easter-eat-ser we would really want to do that but the thing is, this is something Youtube changes on their backend and is actively fighting us. Also we are not the only ones that have this issue. For example, yt-dlp and Newpipe both have these problems (https://github.com/yt-dlp/yt-dlp/issues/11868#issuecomment-2560431566). They also seem to think there might be aggressive IP blocking from Youtube.

We are working on figuring this out and fixing it and applying the same fix to Youtube.

Thank you all for your support and feedback. We really do appreciate it.

**Comment by grappas** [comment]
@Zvonimir-FUTO 
This can be an issue. I had a script in the background with yt-dlp (mpv) for playing background noise 10hrs in a loop. At some point of time this stopped, throwing errors back and forth which made an issue worse for other 3rd party applications (grayjay included). I think this is happening in that case. Playback or not, youtube treats this traffic as bots and there's no way proving that we're not.

**Comment by MikeL270** [comment]
Issue still happens to me everyday.

**Comment by easter-eat-ser** [comment]
Sorry, didn't mean to come off as rude but that's what happens when you write something in the middle of the night. Not trying to be pushy, just wondering why the issue is still shown as closed!! Thank you for working on this, it helps a lot of people

**Comment by easter-eat-ser** [comment]
Noticed that a new update was just pushed to the YouTube plugin! No change in the problem for me, but I'm glad you fixed the 'No signature' issue

**Comment by easter-eat-ser** [comment]
Alright, now this is actually fixed. Thanks for your support!

**Comment by bphd** [comment]
> Also having this issue, only on certain videos (usually videos under 3 minutes long). Experimental UMP is on, no VPN being used, living in the Continental USA, logged in to YouTube. The video also won't download if I try. (Download failed, "no streams for requesting segment 7") The video player acts like I clicked pause, but won't let me click play again. Happens both on Wi-Fi and on Data, so I know it's not an ISP issue or an issue with my home network.
> 
> Edit: earlier this morning I watched videos just fine and this problem only occurred on a few videos, but now it's occurring on every single video I click on, regardless of length, making the app unusable. Same problem also occurs when casting to FCast, only in that instance the video just starts itself over at the 1 minute mark repeatedly. Reinstalling the Grayjay app has not fixed the issue.
> 
> Info: Android 15 Pixel 7 Pro Grayjay version 278 release Github version, not play store version

It goes fine for the first minute of the video, then it starts to re-download the whole video and re-start where it left off. Inreasing how it does it, first time once for few seconds, then more and more until it does it multiple times per seconds and when it's too much he consider the video is finished whatever the place he was and end playing (happens always at the same time, same frequency, same all)

```typescript
[2026-06-18 00:37:45.169] [INFO] [Program] AppContext.BaseDirectory: /gnu/store/2cl8sh5qbmc1h6q4ibshhxa70in9mmlc-grayjay-12/lib/grayjay/
[2026-06-18 00:37:45.197] [INFO] [Program] Base Directory: /home/$USER/.local/share/Grayjay
[2026-06-18 00:37:45.198] [INFO] [Program] Temporary Directory: /home/$USER/.local/share/Grayjay/temp_files
[2026-06-18 00:37:45.202] [INFO] [ManagedThreadPool] New threadpool created (16)
[2026-06-18 00:37:45.265] [INFO] [Program] Log Level: Warning
[2026-06-18 00:37:45.265] [INFO] [Program] Log file path: /home/$USER/.local/share/Grayjay/log.txt
Log flusher exited with exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Grayjay.Desktop.POC.Log.<.ctor>b__7_0()
[2026-06-18 00:37:45.590] [WARNING] [StatePlatform] StatePlatform Initialize
[2026-06-18 00:37:46.379] [WARNING] [StateDownloads] Found 0 redundant downloaded files, deleting
[2026-06-18 00:37:47.362] [ERROR] [V8Converter] FAILED TO PARSE VALUE ON String (Value: [undefined])
[2026-06-18 00:37:47.471] [ERROR] [Program] Failed to check updates
Exception: No updater found
Stack Trace:    at Grayjay.ClientServer.Updater.HasUpdate()
   at Grayjay.Desktop.Program.<>c__DisplayClass13_0.<EntryPoint>b__13()
[2026-06-18 00:37:48.062] [ERROR] [StatePlatform] Home failed for plugin [Rumble]: Captcha required
Exception: Captcha required
Stack Trace:    at Grayjay.Engine.GrayjayPlugin.InterceptExceptions[T](Func`1 act, String script)
   at Grayjay.Engine.GrayjayPlugin.EvaluateRawObject(String script, Boolean nullable)
   at Grayjay.Engine.GrayjayPlugin.EvaluatePager[T](String js, Action`1 modifier)
   at Grayjay.Engine.GrayjayPlugin.<GetHome>b__102_0()
   at Grayjay.Engine.GrayjayPlugin.WithIsBusy[T](Func`1 work)
   at Grayjay.Engine.GrayjayPlugin.GetHome()
   at Grayjay.Desktop.POC.Port.States.StatePlatform.<>c__DisplayClass45_0.<GetHomeLazy>b__1(GrayjayPlugin client)
[2026-06-18 00:37:48.216] [ERROR] [StatePlatform] Home failed for plugin [Kick (Beta)]: Request [https://web.kick.com/api/v1/livestreams?page=1&limit=20&sort=featured_home&language=en] failed with code [403] (Line 328, Col 27)
Exception: Request [https://web.kick.com/api/v1/livestreams?page=1&limit=20&sort=featured_home&language=en] failed with code [403] (Line 328, Col 27)

[2026-06-18 00:38:55.123] [ERROR] [HttpProxy] Failed to handle data.
Exception: No streams for requesting segment 13 (Line 5410, Col 10)
   at Grayjay.Engine.Extensions.InvokeV8(IJavaScriptObject obj, PluginConfig config, String method, Object[] args)
   at Grayjay.Engine.Models.Video.Additions.RequestExecutor.ExecuteRequest(String url, Dictionary`2 headers)
   at Grayjay.ClientServer.Controllers.DetailsController.<>c__DisplayClass32_0.<getRequestExecutorProxy>b__0(HttpProxyRequest req)
   at Grayjay.ClientServer.Proxy.HttpProxySession.RunAsync()
   at Grayjay.ClientServer.Proxy.HttpProxySession.<Start>b__7_0()

[2026-06-18 00:39:58.998] [ERROR] [T] An exception occurred in the IPC
Exception: The operation was canceled.
Stack Trace:    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellatio
nToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at DotCef.DotCefProcess.<Start>b__28_3()
[2026-06-18 00:39:59.003] [ERROR] [T] An exception occurred while handling UDP result: 'The operation was canceled.':    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.SocketReceiveFromResult>.GetResult(Int16 token)
   at System.Net.Sockets.UdpClient.<ReceiveAsync>g__WaitAndWrap|62_0(ValueTask`1 task)
   at FUTO.MDNS.MDNSListener.ReceiveLoopAsync(UdpClient client, CancellationToken cancellationToken) in /home/ubuntu/builds/t2_TNGVSV/0/videostreaming/Grayjay.Desktop/SyncServer/FUTO.MDNS/FUTO.MDNS/MDNSListener.cs:line 268
[2026-06-18 00:39:59.020] [ERROR] [WebSocketEndpoint] Failed to close socket
Exception: The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
Stack Trace:    at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at Grayjay.ClientServer.WebSockets.WebSocketClient.Handle()
[2026-06-18 00:39:59.029] [ERROR] [HttpProxy] Failed to accept client.
Exception: Operation canceled
Stack Trace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
   at System.Net.Sockets.TcpListener.<AcceptTcpClientAsync>g__WaitAndWrap|32_0(ValueTask`1 task)
   at Grayjay.ClientServer.Proxy.HttpProxy.<Start>b__9_0()
```
