### ISSUE TITLE
All videos downloaded within the last couple weeks are corrupted.

### ISSUE THREAD

**Issue by jakecornet** [futo-org/grayjay-android#2243]
### What happened?

I have a playlist that is set to auto-download.  All of the videos I have added to it in the past couple weeks are corrupted.  Short videos (5-6 seconds) don't play at all unless I delete the download.  Longer videos have the last few seconds corrupted in some way: some play thr video fine, but the audio is missing for just the last few seconds; others have issues with the video, too.

Did I change something major that might be causing this?  Maybe, I think this started around the same time I enabled "force experimental UMP streams".  I enabled that to fix the issue with IOS streams where the last second or two of every video is cut off.

### Grayjay Version

306

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

248

### When do you experience the issue?

- [x] While logged in
- [x] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by Zvonimir-FUTO** [comment]
Do you have any way to reproduce this? This is interesting since only iOS streams got cut off at the end but there were no changes from us towards UMP or iOS handling lately.

**Comment by jakecornet** [comment]
In my original post, I noted that I am using the mobile version, not the desktop version, when this happens.  I also am not using a VPN when it happens.  I haven't tried it with a VPN.

As far as reproducing this issue: on my phone, enable force experimental UMP streams, then download a video.  The end of the video will be corrupted somehow.  For example: I just DISABLED force UMP streams and downloaded a 3 min video at 1080p 60 fps with no issue.  I deleted the video, ENABLED force UMP streams, and redownloaded it at the same quality.  The entire video is fine, except for the very end where the video freezes.  The audio is fine, though.  With other videos, I have had the audio not work, but the video was fine, or neither worked, but only ever in the last few seconds (or in the case of very short 4-5 sec videos, the whole video).

**Comment by Zvonimir-FUTO** [comment]
Fixed in v319.

**Comment by aobme** [comment]
Starting with v319 my downloads are all corrupt. They will not play, show only a black screen, and show an invalid time code (-12:-55). Attempting to export these videos freezes the app ux with Exporting 0%..

**Comment by jakecornet** [comment]
> Starting with v319 my downloads are all corrupt. They will not play, show only a black screen, and show an invalid time code (-12:-55). Attempting to export these videos freezes the app ux with Exporting 0%..

I experienced this, too.

**Comment by Zvonimir-FUTO** [comment]
Reverted the changes we made so original issue is present where last few seconds will be cut but at least the downloads will work.

**Comment by jakecornet** [comment]
After waiting a couple months, I tried downloading videos again and the original issue is still present.  Short videos (1-5sec) are unwatchable, and the last 1-5 seconds of long videos are frozen/cut off.

**Comment by aobme** [comment]
There seems to have been another change and now downloads all fail with either "Playback Blocked" or "No streams for requesting segment NNNNNN"

App Version 337
Youtube v288

Videos that i have attempted to download also stall a few minutes into playback and the app tries to reload a few times according to toast notifications and then seems to give up.

IMHO, the dev team might benefit from using the download function to test as it seems more likely to generate faults than normal linear playback. Especially with byte range concurrent downloading turned on.

The original issue of the end of videos missing remained with the last successful downloads i had.

**Comment by Zvonimir-FUTO** [comment]
@aobme this is a separate issue than this and it appears Youtube is not providing you with requested streams for some reason. Are you using a VPN maybe?

**Comment by aobme** [comment]
> [@aobme](https://github.com/aobme) this is a separate issue than this and it appears Youtube is not providing you with requested streams for some reason. Are you using a VPN maybe?

No VPN. I've also tried using a VPN to get around the issue without success.

**Comment by ZakariaX1** [comment]
Hello, just wanted to add on to this, I have been experiencing the same, especially in my downloaded playlists, although the playback sometimes will go ~4 seconds over the actual length of the video (and then the player will freeze) as well as the big where it skips the last ~5/6 seconds of the song which led me to think that maybe the 4 seconds (async?) wait might be accidentally added to the download stream and perhaps the "load time" of the video (so before it downloads but after the async) is why sometimes it'll be 5/6 seconds. When downloading a playlist you'll get a popup from basically every video indicating that its waiting for 4 seconds so might be interesting to have a look at that if you have no other leads

Edit: Other than the skipping issue downloading works great for me, would like to see the randomized wait time between videos option like you can do with yt-dlp arguments

**Comment by ZakariaX1** [comment]
Here's an image example of that latter issue I mentioned, and in case it's relevant I'm on a pixel 10 pro and the video is on background/audio only mode. The app also isn't focussed, but I don't know if that's required to reproduce it. 
EDIT: Had no idea the images were this huge, sized them down, sorry about that!

<img src="https://github.com/user-attachments/assets/e29710b4-08b0-43ea-bac6-6673e1e1a67e" height="800">
<img src="https://github.com/user-attachments/assets/ba96b988-76b5-4c33-b7f4-49fbc834c36d" height="800">

**Comment by Zvonimir-FUTO** [comment]
With new Android streams this should be fixed. Could you update Youtube and test?

**Comment by jakecornet** [comment]
Testing on Grayjay version 340, YT version 297 (latest) with IOS streams disabled and "force UMP streams" enabled, videos stream in their entirety, but are significantly corrupted when downloaded (no audio and last few seconds of video are frozen for a video only 7 sec long).

Testing with IOS streams enabled and "force UMP streams" disabled, the last quarter-second is cut off when streaming, but downloads play in their entirety with no issues and nothing cut-off!

For now, this means for a "perfect experience" I need to disable IOS when streaming, but re-enable it for downloading.  If Grayjay has any intent to fix UMP streams, though, I don't think this issue is closed yet.

**Comment by Zvonimir-FUTO** [comment]
End of video being cut off will be fixed in next release. We will look to improve UMP streams as well since they are probably the only option Youtube will provide in the future.

**Comment by sabata3** [comment]
@Zvonimir-FUTO 
Issue #3108 has popped up again after the most recent YT cipher update.
Has only affected downloads made after that update.
Sometimes video plays but audio cuts, other times both stop but the remaining duration is 'waited' before next in queue plays.

Figured I'd comment on this Open ticket instead of my closed as dupe one.

**Comment by Zvonimir-FUTO** [comment]
This was never fixed for UMP streams, you were just getting Android streams before.

**Comment by Zvonimir-FUTO** [comment]
Can't believe I'm saying this but **fixed**!
Fix will be included in next release! Thank you all for help.

**Comment by bphd** [comment]
> There seems to have been another change and now downloads all fail with either "Playback Blocked" or "No streams for requesting segment NNNNNN"
> 
> App Version 337 Youtube v288
> 
> Videos that i have attempted to download also stall a few minutes into playback and the app tries to reload a few times according to toast notifications and then seems to give up.
> 
> IMHO, the dev team might benefit from using the download function to test as it seems more likely to generate faults than normal linear playback. Especially with byte range concurrent downloading turned on.
> 
> The original issue of the end of videos missing remained with the last successful downloads i had.

It goes fine for the first minute of the video, then it starts to re-download the whole video and re-start where it left off. Inreasing how it does it, first time once for few seconds, then more and more until it does it multiple times per seconds and when it's too much he consider the video is finished whatever the place he was and end playing (happens always at the same time, same frequency, same all)

```typescript
[2026-06-18 00:37:45.169] [INFO] [Program] AppContext.BaseDirectory: /gnu/store/2cl8sh5qbmc1h6q4ibshhxa70in9mmlc-grayjay-12/lib/grayjay/
[2026-06-18 00:37:45.197] [INFO] [Program] Base Directory: /home/$USER/.local/share/Grayjay
[2026-06-18 00:37:45.198] [INFO] [Program] Temporary Directory: /home/$USER/.local/share/Grayjay/temp_files
[2026-06-18 00:37:45.202] [INFO] [ManagedThreadPool] New threadpool created (16)
[2026-06-18 00:37:45.265] [INFO] [Program] Log Level: Warning
[2026-06-18 00:37:45.265] [INFO] [Program] Log file path: /home/$USER/.local/share/Grayjay/log.txt
Log flusher exited with exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Grayjay.Desktop.POC.Log.<.ctor>b__7_0()
[2026-06-18 00:37:45.590] [WARNING] [StatePlatform] StatePlatform Initialize
[2026-06-18 00:37:46.379] [WARNING] [StateDownloads] Found 0 redundant downloaded files, deleting
[2026-06-18 00:37:47.362] [ERROR] [V8Converter] FAILED TO PARSE VALUE ON String (Value: [undefined])
[2026-06-18 00:37:47.471] [ERROR] [Program] Failed to check updates
Exception: No updater found
Stack Trace:    at Grayjay.ClientServer.Updater.HasUpdate()
   at Grayjay.Desktop.Program.<>c__DisplayClass13_0.<EntryPoint>b__13()
[2026-06-18 00:37:48.062] [ERROR] [StatePlatform] Home failed for plugin [Rumble]: Captcha required
Exception: Captcha required
Stack Trace:    at Grayjay.Engine.GrayjayPlugin.InterceptExceptions[T](Func`1 act, String script)
   at Grayjay.Engine.GrayjayPlugin.EvaluateRawObject(String script, Boolean nullable)
   at Grayjay.Engine.GrayjayPlugin.EvaluatePager[T](String js, Action`1 modifier)
   at Grayjay.Engine.GrayjayPlugin.<GetHome>b__102_0()
   at Grayjay.Engine.GrayjayPlugin.WithIsBusy[T](Func`1 work)
   at Grayjay.Engine.GrayjayPlugin.GetHome()
   at Grayjay.Desktop.POC.Port.States.StatePlatform.<>c__DisplayClass45_0.<GetHomeLazy>b__1(GrayjayPlugin client)
[2026-06-18 00:37:48.216] [ERROR] [StatePlatform] Home failed for plugin [Kick (Beta)]: Request [https://web.kick.com/api/v1/livestreams?page=1&limit=20&sort=featured_home&language=en] failed with code [403] (Line 328, Col 27)
Exception: Request [https://web.kick.com/api/v1/livestreams?page=1&limit=20&sort=featured_home&language=en] failed with code [403] (Line 328, Col 27)

[2026-06-18 00:38:55.123] [ERROR] [HttpProxy] Failed to handle data.
Exception: No streams for requesting segment 13 (Line 5410, Col 10)
   at Grayjay.Engine.Extensions.InvokeV8(IJavaScriptObject obj, PluginConfig config, String method, Object[] args)
   at Grayjay.Engine.Models.Video.Additions.RequestExecutor.ExecuteRequest(String url, Dictionary`2 headers)
   at Grayjay.ClientServer.Controllers.DetailsController.<>c__DisplayClass32_0.<getRequestExecutorProxy>b__0(HttpProxyRequest req)
   at Grayjay.ClientServer.Proxy.HttpProxySession.RunAsync()
   at Grayjay.ClientServer.Proxy.HttpProxySession.<Start>b__7_0()

[2026-06-18 00:39:58.998] [ERROR] [T] An exception occurred in the IPC
Exception: The operation was canceled.
Stack Trace:    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellatio
nToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at DotCef.DotCefProcess.<Start>b__28_3()
[2026-06-18 00:39:59.003] [ERROR] [T] An exception occurred while handling UDP result: 'The operation was canceled.':    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.SocketReceiveFromResult>.GetResult(Int16 token)
   at System.Net.Sockets.UdpClient.<ReceiveAsync>g__WaitAndWrap|62_0(ValueTask`1 task)
   at FUTO.MDNS.MDNSListener.ReceiveLoopAsync(UdpClient client, CancellationToken cancellationToken) in /home/ubuntu/builds/t2_TNGVSV/0/videostreaming/Grayjay.Desktop/SyncServer/FUTO.MDNS/FUTO.MDNS/MDNSListener.cs:line 268
[2026-06-18 00:39:59.020] [ERROR] [WebSocketEndpoint] Failed to close socket
Exception: The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
Stack Trace:    at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at Grayjay.ClientServer.WebSockets.WebSocketClient.Handle()
[2026-06-18 00:39:59.029] [ERROR] [HttpProxy] Failed to accept client.
Exception: Operation canceled
Stack Trace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
   at System.Net.Sockets.TcpListener.<AcceptTcpClientAsync>g__WaitAndWrap|32_0(ValueTask`1 task)
   at Grayjay.ClientServer.Proxy.HttpProxy.<Start>b__9_0()
```

**Comment by Zvonimir-FUTO** [comment]
Fixed in v391.
