### ISSUE TITLE
WORKAROUND RELEASED - Playback blocked (OP67:1) - Youtube

### ISSUE THREAD

**Issue by Zvonimir-FUTO** [futo-org/grayjay-android#2351]
### Description

Youtube started rolling out a new mechanism which breaks Youtube plugin in Grayjay.

If you are seeing error `Playback blocked (OP67:1)` you are encountering this problem.

Do **NOT** uninstall the app trying to fix it since it is not related to the app and it will only result in lost data.
You could try to re-enabling the plugin to temporarily fix it, although this might not always work.

We are actively working on a fix as this is our top priority!

Thank you all for your patience and support <3

**Comment by Zvonimir-FUTO** [comment]
We made a workaround in v327. This will give us time to work on the issue while enabling users to enjoy their content with minimum inconvenience of plugin reloading when encountering the issue.

We are unlocking the thread so you can report issues related to the workaround if you encounter any. 
For any other issues related to this release, please open a new issue if you can't find existing one for it.

**Comment by andreasgrimm** [comment]
The workaround in v327 doesn't seem to work when you depend on "Allow Loginfallback".

**Comment by lucastheguyy** [comment]
Workaround seems to not do anything then crash the app if you check the sources list

**Comment by Meganium97** [comment]
Workaround is functional visually but current effectivity is 0 for me. No different than 321.

**Comment by Zvonimir-FUTO** [comment]
> The workaround in v327 doesn't seem to work when you depend on "Allow Loginfallback".

Not sure how this is related. From my testing it works logged in or out and isn't related to it at all.

> Workaround seems to not do anything then crash the app if you check the sources list

Could you elaborate a bit more on how to reproduce the crash? I wasn't able to reproduce this.

> Workaround is functional visually but current effectivity is 0 for me. No different than 321.

Occasionally it might not succeed with multiple retries but if you play another video and try again it should work. At least from my testing.

---

Anyway, we are working on a permanent fix instead of a workaround. But with the low reproducibility, it will take some time to figure it out.

**Comment by riscos-richard** [comment]
For what it's worth, I for the last week-ish, I've found that Grayjay would only load one YouTube video.  Any subsequent videos would fail to play, and I had to restart the app.  I noticed that if a played videos from a non-monetised channel (which doesn't show ads) then I was able to play multiple videos.  Makes sense, I suppose, if YouTube are going after 'ad blockers'.

For the last day, with this new workaround, it's working happily.  I can play multiple videos without restarting the app.  You still see a 'blocked' pop-up, and that the YT plugin is restarting itself (the workaround, I guess), but the user experience is that it now works.

So thumbs up for the workaround - many thanks for delivering it so quickly.

**Comment by lucastheguyy** [comment]
> > Workaround seems to not do anything then crash the app if you check the sources list
> 
> Could you elaborate a bit more on how to reproduce the crash? I wasn't able to reproduce this.

i think it happens if you check shortly afterwards the plugin starts to reload

**Comment by Zvonimir-FUTO** [comment]
> > > Workaround seems to not do anything then crash the app if you check the sources list
> > 
> > 
> > Could you elaborate a bit more on how to reproduce the crash? I wasn't able to reproduce this.
> 
> i think it happens if you check shortly afterwards the plugin starts to reload

Wasn't able to reproduce it. Could you please open a new issue for this and provide some logs inside it?

**Comment by i-am-captain** [comment]
The workarounds don't work for me. The plugin reloads twice, but the video stays black. I enabled logging at maximum level, opened one video, let it fail and then sent the logs. The ID of the sent logs is 723327d4-6c45-4e1c-96d6-88bbdcddb0ec. Maybe this helps.
On another note, newpipe works fine, maybe they found another fix, but don't know if you could borrow that because of gpl and stuff. Not throwing shade though, i like grayjay way more.

**Comment by Zvonimir-FUTO** [comment]
We are working on a better version of workaround with slight delay. We are still testing how the Youtube behaves but it appears that if you reload after X amount of seconds it works.

Logs won't help in this case but thank you for providing them anyway. 

As far as we are familiar, nobody found a technical fix yet, just workarounds. Also other projects are quite different from us when it comes to implementation.

**Comment by rostby** [comment]
Is this workaround in the desktop version yet, and i understand this is the android versions github, but the desktops issue is closed as duplicate

**Comment by Zvonimir-FUTO** [comment]
Not in desktop yet. But don't worry we didn't forgot about desktop.

**Comment by andreasgrimm** [comment]
> Not sure how this is related. From my testing it works logged in or out and isn't related to it at all.

Me neither, as currently I'm only able to test for the scenario in which without being logged in, YT would say: "Please log in to prove you're not a bot" (or something along those lines). Thus I only wanted to mention that it is under this specific scenario, not necessarily that it has something to do with it.

**Comment by andreasgrimm** [comment]
On another note: So far for me in case when the error

> Playback blocked (OP67:1)

... gets displayed and I'm not able to play the video directly within Graynay, what always worked for me is to select "Page" from the video's menu and where a web view is being used.
The video plays perfectly fine every time and obviously my authenticated session is being used there as well. I'm just not able to bring the video to full screen. But for anyone that has the same problem as me, where almost no videos can be played, currently this might be another workaround. Of course you're missing out on all the other Grayjay functions in regards to the video and Grayjay's playback history and so on. But hey, It might help out some of you 😊

**Comment by andreasgrimm** [comment]
> Not sure how this is related. From my testing it works logged in or out and isn't related to it at all.

I'm using a network connection that forces YT to say  "Please log in to prove you're not a bot" (or something along those lines). Thus I'm using an authenticated session. Trying to watch a specific video, I always get the error: Playback blocked (OP67:1).

On a friend's device, using a different network connection that doesn't enforce to be authenticated, trying to watch this specific video, no error occurs.

Both using the latest version of Grayjay.

I hope this is useful in regards to the repro. Because using a network connection with which YT doesn't enforce you to use an authenticated session but you still do, isn't the same as using a network connection with which YT does enforce you to use an authenticated session.

**Comment by muizzsiddique** [comment]
I have to say, once I disabled the Verify IOS playback, this reloading workaround has made IOS streams more playable for me. Even if only a minute loads, it will eventually reload enough times to load the whole video.

This hasn't done anything to improve playback for UMP streams, though.

**Comment by ghost** [comment]
I can play all videos with the following setup. 

1. Used a wireguard cloudflare warp setup with RethinkDNS to change IP (https://rethinkdns.com/)
2. Disabled Force Experimental UMP Strems option in grayjay

Got the idea to change the ip from @andreasgrimm reply earlier. So, tried the approach with Grayjay desktop and protonvpn free. Few servers were unable to play videos with different errors in Grayjay app. A Poland server was able to play the videos. I had bypassed youtube playback issues in pipepipe app using the above RethinkDNS setup earlier this week in android. So, tried the same setup again with Grayjay android. It's a mix of IOS and UMP streams now. Sometimes plugin reloads but playback is fine. Reproduced the same setup in Grayjay Desktop with wireguard configured in Gnome. It's working. 


Update: Works without any workarounds with latest plugin update. v256

**Comment by RZ22F** [comment]
Thank you.
Works flawlessly.
Date: Jun 22, 2025.
Noted date for posterity.
Will note down anything of relevance here.

**Comment by PseudoMortus** [comment]
Still having issues on my end (using latest versions), but I have noticed (for me at least) each time the issue pops up (which seems to be approx every 24 hrs) if I toggle the login bits (Use Login for Channels and Use Login for Details) then it works for another 24 hrs or so. Comes back, toggle them again, we're back on track, that sort of thing.

**Comment by Zvonimir-FUTO** [comment]
Improved the handling in the latest update. Everything should work now. 
I'll leave the issue opened for some time to give you a chance to report issues if you find some.

Edit:
Forgot to mention that we recommend enabling the following settings:

- Allow UMP to reload plugin
- Use isInlinePlaybackNoAd

**Comment by Zvonimir-FUTO** [comment]
> Having issues regarding subtitles as there is no subtitles for any video that is playing.

Not related. Check #2216

**Comment by PseudoMortus** [comment]
Over 24 hrs later and seemingly 1 irrelevant interruption, holding steady on my end.

**Comment by jonathancutting** [comment]
Worked for a hot second, but YouTube caught on somehow. I'm still getting the playback blocked error on almost every YouTube video. When a video does play, the next video is always blocked. Have tried with VPN on and off, casting and not casting. I can't download at all from YouTube (always UMP choices, and always blocked). Using plugin version 258.

**Comment by rostby** [comment]
> Worked for a hot second, but YouTube caught on somehow. I'm still getting the playback blocked error on almost every YouTube video. When a video does play, the next video is always blocked. Have tried with VPN on and off, casting and not casting. I can't download at all from YouTube (always UMP choices, and always blocked). Using plugin version 258.

same here on grayjay desktop

**Comment by Zvonimir-FUTO** [comment]
@rostby The workaround has not been implemented for desktop yet.

> Worked for a hot second, but YouTube caught on somehow. I'm still getting the playback blocked error on almost every YouTube video. When a video does play, the next video is always blocked. Have tried with VPN on and off, casting and not casting. I can't download at all from YouTube (always UMP choices, and always blocked). Using plugin version 258.

@jonathancutting could you share your Youtube settings? To be clear playback blocked error shows up from time to time but the workaround should work and play the video after few seconds.

**Comment by jonathancutting** [comment]
@Zvonimir-FUTO Screenshots attached. Sorry, I couldn't figure out how to export the plugin settings as JSON from Android.

When I get the "playback blocked" error, it's followed by a "trying workaround" message, but it doesn't start playing, even if I let it sit there for over a minute.

[YouTube-plugin-settings.zip](https://github.com/user-attachments/files/21008694/YouTube-plugin-settings.zip)

**Comment by Zvonimir-FUTO** [comment]
@jonathancutting No worries, that is actually our fault since we didn't implement any easy way for users to export plugin settings so we clog the issues with huge vertical screenshots. I see you were thinking ahead and put it into a zip :)

Could you try testing with **Allow UMP experimental backoff** enabled?

**Comment by Zvonimir-FUTO** [comment]
@VikFreeze Desktop version doesn't have the workaround available yet. Hate to hide it as "Spam" but there are really no better label options...

**Comment by VikFreeze** [comment]
> [@VikFreeze](https://github.com/VikFreeze) Desktop version doesn't have the workaround available yet. Hate to hide it as "Spam" but there are really no better label options...

Sorry, wrong repo

**Comment by Zvonimir-FUTO** [comment]
New version of Grayjay (330) and Youtube (262) have been released!

We have improved the workaround so now you should either see plugin reloads or backing off for a few seconds before video plays.

With this most of the issues regarding playback on Youtube should be resolved. 
Please test and report if you encounter any bugs.

- Note that the workaround is not released yet for desktop! That is next on the menu.
- Subtitles still don't work. This is coming after desktop release. But it was blocked by some work that was finally done in this update. #2216
- If you are using VPN, you might encounter "Video Unplayable" error. Refer to #2384

**Comment by jonathancutting** [comment]
> Could you try testing with **Allow UMP experimental backoff** enabled?

@Zvonimir-FUTO Tried that, but it didn't seem to make a difference regarding this particular issue. However, the latest updates (GrayJay v330, YouTube plugin v262) appear to have fixed the issue. I was able to watch several videos this afternoon without seeing the "playback blocked" error. Something to note is that I haven't tried yet watching multiple videos from a playlist. YouTube seems to hate playing from playlists more than single videos (prior to this update).

There are a couple other new playback things going on, but I believe those are separate issues—I'll open separate issues for those, if I can't figure them out myself.

**Comment by Zvonimir-FUTO** [comment]
I would suggest disabling "_Use isInlinePlaybackNoAd_" and "_Allow experimental UMP backoff_" if you had enabled it previously.

Seems Youtube patched out isInlinePlaybackNoAd.

Make sure to keep "_Allow experimental UMP backoff **(async)**_".

**Comment by VikFreeze** [comment]
Ive gone thru a 8 video playlist. The video froze 3 times(waited for 1+ minute), moving the cue a small bit forward resumed playing.
I got a prompt to reload on the last video, clicked yes for about 5 times and the video eventually played.
Also, when videos in a list started to refresh, there is no prompt, it refreshed a few times then skips to the next video in the list, a prompt is only presented if its the last video in the list

**Comment by Zvonimir-FUTO** [comment]
> Ive gone thru a 8 video playlist. The video froze 3 times(waited for 1+ minute), moving the cue a small bit forward resumed playing. I got a prompt to reload on the last video, clicked yes for about 5 times and the video eventually played. Also, when videos in a list started to refresh, there is no prompt, it refreshed a few times then skips to the next video in the list, a prompt is only presented if its the last video in the list

is this on desktop?

**Comment by Zvonimir-FUTO** [comment]
Per my previous comment:

> - Note that the workaround is **not released yet for desktop**! That is next on the menu.

**Comment by mombiushibachi** [comment]
Hi, I have the same issue, where Youtube is blocking the video from playing. It will play for ~5 seconds, then I get the error message.

I just noticed that it is not yet ready for desktop (which is what I am using), so will wait patiently :).

For anyone else using Youtube waiting for the fix, a workaround I use on Youtube's site to watch videos without ad's is to save them to 'Watch Later', then open them from there. I can then watch the videos without issue. Hopefully that might help some people while waiting for the workaround on desktop :).

**Comment by Zvonimir-FUTO** [comment]
Fixes added in new (v9) desktop version. Youtube playback should work on desktop now.

Things we are working on next (and some other Youtube fixes):

- https://github.com/futo-org/grayjay-android/issues/2216
- https://github.com/futo-org/Grayjay.Desktop/issues/583
