### ISSUE TITLE
Bug: android picture in picture videos lose play state

### ISSUE THREAD

**Issue by RustyHearth** [futo-org/grayjay-android#2689]
### Reproduction steps

1. Play youtube video
2. Try to play or stop video
3. Minimize video to be on picture in picture as overlay
4. Try to stop or play video when minimized
5. Video windows disappears
6. When entering app again video and queue lost

### Actual result

Occasionally when stopping or playing a youtube video and I minimize it to small windows overlay, the state off video is lost, when minimized if the video is not playing you can see it's stuck on pause icon. When pressing the video's pause button it stays minimized but shows the full app inside that windows, trying to enter the app the played video disappears and the queue it had. Also, sometimes the video can be played and minimized video won't show until I change to new video

### Expected result

I expect the state of video to stay the same across the apps life time whether  it is minimized or on full display. Something in the state isn't changing 

### Grayjay Version

336

### What plugins are you seeing the problem on?

YouTube

### Plugin Version

279

### Which android version are you using?

Android 15

### Which device are you using?

Samsung

### Which operating system are you using?

Stock android

### When do you experience the issue?

- [x] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by Zvonimir-FUTO** [comment]
Related to #2679

**Comment by RustyHearth** [comment]
> Related to [#2679](https://github.com/futo-org/grayjay-android/issues/2679)

In which version it's expected to be solved on?, I see the related issue was open on version 330 but I'm already on 336. I experienced it for quite a while

**Comment by Zvonimir-FUTO** [comment]
Oh I didn't even noticed user was on older version. There was a fix for in 336 but seems there are still some edge cases that we need to look into.

**Comment by RustyHearth** [comment]
> > Oh I didn't even noticed user was on older version. There was a fix for in 336 but seems there are still some edge cases that we need to look into.
> 
> There is one case I can find with high-reproduceable rate: You run the video till the end of it (run as normal or fast forward to near end), while in PiP mode. When video ends, you press the play/pause button (the button is in pause icon in this case) and the video is gone.

I don't always notice if its reproduced in the end of video because either i have a queue or i jump between videos before they end, but the two main ways i reproduce the problem:
First scenario
1. Play video
2. Pause video (can be played again before PiP mode, seems at least on pause action needed)
3. Minimize to PiP
4. Press pause in PiP mode
5. Video is gone and it shows all app inside PiP mode
6. Try to enlarge and the video gone

Second scenario:
1. Play video
2. Minimize to PiP 
3. Pause video
4. Maximize video
5. Play again
6. Minimize to PiP
7. Video doesn't show in PiP mode but keeps playing

It seems maybe when the video is paused it doesn't translate between the two modes.

**Comment by alphanightshift** [comment]
> > > Oh I didn't even noticed user was on older version. There was a fix for in 336 but seems there are still some edge cases that we need to look into.
> > 
> > 
> > There is one case I can find with high-reproduceable rate: You run the video till the end of it (run as normal or fast forward to near end), while in PiP mode. When video ends, you press the play/pause button (the button is in pause icon in this case) and the video is gone.
> 
> I don't always notice if its reproduced in the end of video because either i have a queue or i jump between videos before they end, but the two main ways i reproduce the problem: First scenario
> 
> 1. Play video
> 2. Pause video (can be played again before PiP mode, seems at least on pause action needed)
> 3. Minimize to PiP
> 4. Press pause in PiP mode
> 5. Video is gone and it shows all app inside PiP mode
> 6. Try to enlarge and the video gone
> 
> Second scenario:
> 
> 1. Play video
> 2. Minimize to PiP
> 3. Pause video
> 4. Maximize video
> 5. Play again
> 6. Minimize to PiP
> 7. Video doesn't show in PiP mode but keeps playing
> 
> It seems maybe when the video is paused it doesn't translate between the two modes.

Can confirm first scenario happens, though it is very rare.

**Comment by alphanightshift** [comment]
> > > > > Oh I didn't even noticed user was on older version. There was a fix for in 336 but seems there are still some edge cases that we need to look into.
> > > > 
> > > > 
> > > > There is one case I can find with high-reproduceable rate: You run the video till the end of it (run as normal or fast forward to near end), while in PiP mode. When video ends, you press the play/pause button (the button is in pause icon in this case) and the video is gone.
> > > 
> > > 
> > > I don't always notice if its reproduced in the end of video because either i have a queue or i jump between videos before they end, but the two main ways i reproduce the problem: First scenario
> > > 
> > > 1. Play video
> > > 2. Pause video (can be played again before PiP mode, seems at least on pause action needed)
> > > 3. Minimize to PiP
> > > 4. Press pause in PiP mode
> > > 5. Video is gone and it shows all app inside PiP mode
> > > 6. Try to enlarge and the video gone
> > > 
> > > Second scenario:
> > > 
> > > 1. Play video
> > > 2. Minimize to PiP
> > > 3. Pause video
> > > 4. Maximize video
> > > 5. Play again
> > > 6. Minimize to PiP
> > > 7. Video doesn't show in PiP mode but keeps playing
> > > 
> > > It seems maybe when the video is paused it doesn't translate between the two modes.
> > 
> > 
Can confirm first scenario happens, though it is very rare (like dozens of times of doing this and this would happen once). Pausing the video in PiP then turn off the screen for a while before play the video again can happen with more percentage.

**Comment by RustyHearth** [comment]
> > > > > > Oh I didn't even noticed user was on older version. There was a fix for in 336 but seems there are still some edge cases that we need to look into.
> > > > > 
> > > > > 
> > > > > There is one case I can find with high-reproduceable rate: You run the video till the end of it (run as normal or fast forward to near end), while in PiP mode. When video ends, you press the play/pause button (the button is in pause icon in this case) and the video is gone.
> > > > 
> > > > 
> > > > I don't always notice if its reproduced in the end of video because either i have a queue or i jump between videos before they end, but the two main ways i reproduce the problem: First scenario
> > > > 
> > > > 1. Play video
> > > > 2. Pause video (can be played again before PiP mode, seems at least on pause action needed)
> > > > 3. Minimize to PiP
> > > > 4. Press pause in PiP mode
> > > > 5. Video is gone and it shows all app inside PiP mode
> > > > 6. Try to enlarge and the video gone
> > > > 
> > > > Second scenario:
> > > > 
> > > > 1. Play video
> > > > 2. Minimize to PiP
> > > > 3. Pause video
> > > > 4. Maximize video
> > > > 5. Play again
> > > > 6. Minimize to PiP
> > > > 7. Video doesn't show in PiP mode but keeps playing
> > > > 
> > > > It seems maybe when the video is paused it doesn't translate between the two modes.
> 
> Can confirm first scenario happens, though it is very rare (like dozens of times of doing this and this would happen once). Pausing the video in PiP then turn off the screen for a while before play the video again can happen with more percentage.

Interesting, since I can reproduce it every time. I don't remember making any special changes in app, but maybe it has to do with youtube videos.

**Comment by Zvonimir-FUTO** [comment]
Thanks for info guys, will look into it.

**Comment by Zvonimir-FUTO** [comment]
Will be fixed in the next release.

**Comment by Zvonimir-FUTO** [comment]
Should be fixed in v340.

**Comment by RustyHearth** [comment]
> Should be fixed in v340.

Hi, sorry for late response, thank you for the update, the first scenario got fixed, but wanted to update you that the second scenario where pausing PiP and and exiting PiP makes PiP disappear still happens

**Comment by Zvonimir-FUTO** [comment]
@RustyHearth Thank you for the feedback. Could you please open a separate issue for it since this one is already bloated?
