### ISSUE TITLE
Bug: YouTube Plugin Failure to Play

### ISSUE THREAD

**Issue by Stormer13** [futo-org/grayjay-android#2712]
### Reproduction steps

1. Select a YouTube video to play that is NOT already downloaded. 
2. Grayjay tries to load it for a few seconds. 
3. Grayjay fails to load video.
4. This extends to downloading YouTube videos as well. 

### Actual result

An error message occurs, as seen below, and the video does not play or download.
"Failed to load video (ScriptException)
Plugin [YouTube]
[YouTube] N Decryptor was not available [/s/player/2b83d2e0/player_ias.vflset/en_US/base.js] (7968) [2-3]" 

### Expected result

YouTube will play or download the video. 

### Grayjay Version

336

### What plugins are you seeing the problem on?

YouTube

### Plugin Version

279

### Which android version are you using?

Android 16

### Which device are you using?

Google Pixel 9a

### Which operating system are you using?

Android OS

### When do you experience the issue?

- [x] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

No

### References

Rumble videos still work fine. Further, the issue resolved itself by logging out and logging back in. I wanted to bring it up in case this was an issue for anyone else though or in case it's a sign of a possible issue. 

### Relevant log output

```shell

```

**Comment by Keyaku** [comment]
**EDIT 2**: Never mind the log out + logging back in. It worked for a day, but stopped working halfway through yesterday. This includes Privacy Mode, which behaves the same now.

~~**EDIT**: Logging out then logging back in fixes the N Decryptor error.
However, the 1:00 issue still persists while logged in.~~

---
**Original comment**:

Adding to this: this happens to me while logged in to the YouTube plugin.
Using Privacy Mode bypasses this problem (in fact, it also bypasses the 1:00 problem which I've been having lately).

**Comment by flexxyfluxx** [comment]
I have also been unable to play yt videos on plugin version 281(Grayjay version 336).

Video appears to load (throbber appears), but fails after a few seconds. Comments do load, though.

I've been observing the following debug messages, consistently in this order:
- "Using advance obfuscation cipher"
- "Falling back to virtualized player"
- "Using YTSession client"
- "YTSessionClient got pot [some varying sequence of characters]" (this message repeats a few times with different characters each time, and sometimes with "(auth)" before the square bracket part)

Previously mentioned mitigation of using Privacy Mode does not work for me.
I have not tried downloading, as of now.

..edit1: spelling

..edit2: logging out and in again also does not work for me.

**Comment by exaltotun** [comment]
I have the same issue, can't seem to play youtube videos in the app on android. I was not logged in to begin with but tried logging in and out still the same errors as described by Flexxy above. 

youtube plugin version 281

**Comment by The-Exnor** [comment]
Same issue here. Even on privacy mode i cant  play or download any YouTube video.  
Using version 336 ( apk sideloaded, not the Playstore version).

**Comment by DigitalFunk** [comment]
I got it to work by disabling "Allow Loginfallback" in the plugin settings.

**Comment by cypheir** [comment]
Mine has been doing this since yesterday. There was a youtube plugin update this morning. It worked fine after installing the update until about 2 hours ago. Now it's doing the same thing again.

**Comment by Zvonimir-FUTO** [comment]
Original issue has been fixed in v281. We are investigating other reports.

**Comment by Keyaku** [comment]
> Original issue has been fixed in v281. We are investigating other reports.

Currently in v281, and I don't know what part of the original issue was fixed. The "N Decryptor" message still persists.

I also have to retract my previous statement: like @cypheir's [case](https://github.com/futo-org/grayjay-android/issues/2712#issuecomment-3326861027), it worked up until sometime during yesterday (23 September).
Same with today, the message "Using advanced obfuscated cipher" is spammed before it refuses to play any video.

**Comment by Zvonimir-FUTO** [comment]
Interesting, will look into that as well I guess.

**Comment by Keyaku** [comment]
@Zvonimir-FUTO Other than enabling "Allow Developer Submissions", is there anything else we can do to help debug this?

**Comment by Figim** [comment]
> Interesting, will look into that as well I guess.

A new http 403 error has occurred. Youtube has changed something 

Freetube will release the solution. Ytdlp is also affected 

https://github.com/FreeTubeApp/FreeTube/issues/8083

https://github.com/yt-dlp/yt-dlp/issues/14421

**Comment by izzaclippy** [comment]
For me it sometimes works. I've found that the first video I load works, but I have to close and reopen the app to watch another one. It's also affecting the desktop app.

**Comment by MattFischer92** [comment]
My issue is similar with the YouTube plugin version 281 and app version 336, although i see "using advanced obfuscated cipher" then "failing back to virtualized player" and then it just doesn't load. I have also tried signing out and back in with the added step of force stopping the side loaded app clearing cache on the app and relaunching, then in private mode, then toggling on and off all the other settings like ump. I even tried verifying with content for kids to ensure it was not age checks. Looks like google is playing cat and mouse again because they are not rich and powerful enough yet. 

"Edit"

I noticed without touching anything or signing in the Play store version worked last week then randomly over the weekend the side loaded one started working. Sadly now however it's not working on either with the same issue "using advanced obfuscated cipher" then "failing back to virtualized player" and the source plugin for YouTube on version 285.

Regular YouTube works so this is clearly an issue with Grayjay.

**Comment by Zvonimir-FUTO** [comment]
Cipher issue fixed in 282. We are still looking into playback issue which appears to be a widespread issue among other apps as well.

We have a lead where the issue lies and we are prioritizing this above everything else. Stay tuned.

**Comment by flexxyfluxx** [comment]
Tested 282: Continues to be borked on my end. Same symptoms as I outlined above.

Will try some of the proposed workarounds tho; maybe one of those works now.

**Comment by Zvonimir-FUTO** [comment]
@flexxyfluxx you still get the cipher error?

**Comment by flexxyfluxx** [comment]
@Zvonimir-FUTO yep.

progression of debug messages continues to be:
- "Using advance obfuscation cipher"
- "Falling back to virtualized player" (2x now)
- "Using YTSession client"
- "YTSessionClient got pot [some varying sequence of characters]" (this message repeats a few times with different characters each time, and sometimes with "(auth)" before the square bracket part)

**Comment by Zvonimir-FUTO** [comment]
Can you screenshot the error message? That doesn't look like cipher issue. Think you are referring to playback issue with 403 error code.

For cipher issue there should be a pop up window saying something like `YouTube] N Decryptor was not available [/s/player/2b83d2e0/player_ias.vflset/en_US/base.js] (7968) [2-3]`

**Comment by flexxyfluxx** [comment]
..oh yeah, that is a different error from what i'm getting. sorry if i created some confusion.

**Comment by Keyaku** [comment]
> For cipher issue there should be a pop up window saying something like `YouTube] N Decryptor was not available [/s/player/2b83d2e0/player_ias.vflset/en_US/base.js] (7968) [2-3]`

I still get this error on v282. Tried logging out then back in, and even Privacy mode, but no dice. Same error, on any YouTube video from my home feed.

YouTube is definitely cooking...

**Comment by Zvonimir-FUTO** [comment]
@Keyaku could you screenshot the exact error you get?

**Comment by Keyaku** [comment]
> could you screenshot the exact error you get?

![n decryptor error popup](https://github.com/user-attachments/assets/7624c334-96fe-4d20-ad95-a0d93ef99252)

**Comment by randomgosuser** [comment]
I am having the same issues described in this thread and turning off my VPN fixes it if I am also logged in. If I turn my VPN back on I get the same obfuscated spam message that others are reporting

**Comment by Zvonimir-FUTO** [comment]
@Keyaku Could you check if the setting **Fallback with Player Script** is enabled under Youtube plugin settings? It's the one at the bottom.

**Comment by NormanMises** [comment]
> @Keyaku Could you check if the setting **Fallback with Player Script** is enabled under Youtube plugin settings? It's the one at the bottom.

I don't know what the best settings are for this plugin, as many options are incomprehensible.

**Comment by Keyaku** [comment]
> Could you check if the setting **Fallback with Player Script** is enabled under Youtube plugin settings? It's the one at the bottom.

That option made a difference in my case with v282! I did test that one with the previous versions (except v281) but it would fail all the same.

For now, that option saves it, thank you! I wonder how long it'll last comsidering the hectic last few days.

**Comment by Zvonimir-FUTO** [comment]
> > [@Keyaku](https://github.com/Keyaku) Could you check if the setting **Fallback with Player Script** is enabled under Youtube plugin settings? It's the one at the bottom.
> 
> I don't know what the best settings are for this plugin, as many options are incomprehensible.

Default values are the best usually. You probably shouldn't touch things you don't understand.

**Comment by Keyaku** [comment]
@Zvonimir-FUTO I've got a bit of bad news: the virtualized player solution only works for one video; I then must restart the app to load another one. Every time.

**Comment by Zvonimir-FUTO** [comment]
> [@Zvonimir-FUTO](https://github.com/Zvonimir-FUTO) I've got a bit of bad news: the virtualized player solution only works for one video; I then must restart the app to load another one. Every time.

that's cuz that issue hasn't been fixed yet so UMP streams will fail while iOS streams work.
But the cipher error is not present anymore after enabling Fallback with Player Script?

**Comment by Keyaku** [comment]
> But the cipher error is not present anymore after enabling Fallback with Player Script?

That is correct, and for that I give you my thanks!

**Comment by Zvonimir-FUTO** [comment]
We are looking into the issue still. Rabbit hole goes a bit deeper than expected.
We currently don't need any additional info so please refrain from flooding the issue with comments.

Once we get it working we will update everyone here and release the new version.
Thank you all for feedback and patience.

**Comment by Zvonimir-FUTO** [comment]
Thank all for your patience and for not spamming the issue!

Rabbit hole went deeper than expected and after rough two days of debugging this we managed to fix the playback issue when receiving 403 error code.
We are still encountering playback stop at around 60 seconds so we are still looking into this. Hopefully we get both fixed soon and release an updated version.

**Comment by Kelvin-FUTO** [comment]
We are unaffected by the n-sig problem YT-DLP is having, our system can already deal with the issue they are facing.
We also don't use BG_Utils, we have our own implementation for POT.
I'm not 100% sure, but I believe NewPipe still relies on CDN sources instead of sABR. Which means it doesn't work on some IPs (less trusted ones, and ipv6, etc). They are going to need to support sABR sooner or later.

Grayjay also supports CDN sources, meaning that it still works on trusted ips, but if those fail it will fallback to sABR, which is having the issue we're facing atm.

We've already found the solution, but we think there is a partial rollout, so it is currently hit-or-miss, we're seeing if we can find a way to differentiate it.. We might release the hit or miss solution if we don't find anything quick now.

**Comment by Nullcaller** [comment]
I've encountered a seemingly related issue (GJ v336, YT plugin v282, VPN). Videos don't load past first minute, downloads don't work either, except sometimes they all do. All of the times they have loaded past the first minute I have also been able to download the videos, and the download menu suggested that IOS playback was being used. I've disabled the 'Verify IOS Playback' option in plugin settings, and since doing that had way better luck with some amount of downloads. This is obviously nothing conclusive, though. I'm just leaving this here as a possible solution that may help someone.

**Comment by RyanKet** [comment]
> I've encountered a seemingly related issue (GJ v336, YT plugin v282, VPN). Videos don't load past first minute, downloads don't work either, except sometimes they all do. All of the times they have loaded past the first minute I have also been able to download the videos, and the download menu suggested that IOS playback was being used. I've disabled the 'Verify IOS Playback' option in plugin settings, and since doing that had way better luck with some amount of downloads. This is obviously nothing conclusive, though. I'm just leaving this here as a possible solution that may help someone.

I just disabled "Verify IOS Playback" with my Grayjay thing, and my videos are now playing past 60 seconds now. Again, will work for now until they get their solution out.

**Comment by RyanKet** [comment]
> > I've encountered a seemingly related issue (GJ v336, YT plugin v282, VPN). Videos don't load past first minute, downloads don't work either, except sometimes they all do. All of the times they have loaded past the first minute I have also been able to download the videos, and the download menu suggested that IOS playback was being used. I've disabled the 'Verify IOS Playback' option in plugin settings, and since doing that had way better luck with some amount of downloads. This is obviously nothing conclusive, though. I'm just leaving this here as a possible solution that may help someone.
> 
> I just disabled "Verify IOS Playback" with my Grayjay thing, and my videos are now playing past 60 seconds now. Again, will work for now until they get their solution out.

Okay, it only worked for one video and then it's stopping on 60 seconds again.

**Comment by Figim** [comment]
Ytdlp: Looks to be an A/B test by YouTube of binding the GVS PO Token to the video id instead of session. 
Fix: https://github.com/yt-dlp/yt-dlp/pull/14471

**Comment by Kelvin-FUTO** [comment]
> Ytdlp: Looks to be an A/B test by YouTube of binding the GVS PO Token to the video id instead of session. Fix: [yt-dlp/yt-dlp#14471](https://github.com/yt-dlp/yt-dlp/pull/14471)

Jup, thats what I ment by it being hit or miss atm.
We found that, and had to fix some issues in our async implementation in Android, which caused some issues for the new logic.

This however has now all been solved and we're rolling out a new Android version as we speak that has the new Youtube version embedded into it. Later we will also roll out this Youtube version with a message telling people to update their app.

**Comment by Figim** [comment]
> > Ytdlp: Looks to be an A/B test by YouTube of binding the GVS PO Token to the video id instead of session. Fix: [yt-dlp/yt-dlp#14471](https://github.com/yt-dlp/yt-dlp/pull/14471)
> 
> Jup, thats what I ment by it being hit or miss atm. We found that, and had to fix some issues in our async implementation in Android, which caused some issues for the new logic.
> 
> This however has now all been solved and we're rolling out a new Android version as we speak that has the new Youtube version embedded into it. Later we will also roll out this Youtube version with a message telling people to update their app.

Will you also support the ytdlp Duno feature? 🤔
Or is there no need for grayjay yet, as you already mentioned? 

https://github.com/yt-dlp/yt-dlp/pull/14157#issuecomment-3342185454

Uses: https://github.com/yt-dlp/ejs

Wiki: https://github.com/yt-dlp/yt-dlp-wiki/pull/63

**Comment by Kelvin-FUTO** [comment]
> > > Ytdlp: Looks to be an A/B test by YouTube of binding the GVS PO Token to the video id instead of session. Fix: [yt-dlp/yt-dlp#14471](https://github.com/yt-dlp/yt-dlp/pull/14471)
> > 
> > 
> > Jup, thats what I ment by it being hit or miss atm. We found that, and had to fix some issues in our async implementation in Android, which caused some issues for the new logic.
> > This however has now all been solved and we're rolling out a new Android version as we speak that has the new Youtube version embedded into it. Later we will also roll out this Youtube version with a message telling people to update their app.
> 
> Will you also support the ytdlp Duno feature? 🤔 Or is there no need for grayjay yet, as you already mentioned?
> 
> [yt-dlp/yt-dlp#14157 (comment)](https://github.com/yt-dlp/yt-dlp/pull/14157#issuecomment-3342185454)
> 
> Uses: https://github.com/yt-dlp/ejs
> 
> Wiki: [yt-dlp/yt-dlp-wiki#63](https://github.com/yt-dlp/yt-dlp-wiki/pull/63)

As mentioned before, we don't have the issue that YT-DLP has that would require Deno.

Grayjay already runs plugins in a full V8 sandboxed runtime, meaning this is not needed for us.

**Comment by Zvonimir-FUTO** [comment]
Fixed in the latest version of Youtube and Grayjay on android. Please make sure to update Grayjay as well since the plugin won't work if you are not on the latest version.

Please give us some feedback on the latest version on android while we are finishing up desktop release.

**Comment by Figim** [comment]
> Fixed in the latest version of Youtube and Grayjay on android. Please make sure to update Grayjay as well since the plugin won't work if you are not on the latest version.
> 
> Please give us some feedback on the latest version on android while we are finishing up desktop release.

I just played a 30 minute video. The video stopped in the middle and I couldn't play it again. The video doesn't play when you click the Play button.  I can't play videos anymore. I did not change the plugin settings. 

The bug I'm getting is different. I've updated the app and plugin and the bug I wrote above is still happening. The app plays videos with the updated plugin on first login. However, when I fast forward the video shortly after, the video stops. You can no longer play any videos and the play button doesn't work.

But the comments are loading

**Comment by Figim** [comment]
I've already cleared the app data and the videos don't play on startup. It wasn't like that before. The bug used to happen a little later, but it doesn't play at all anymore.

**Comment by Zvonimir-FUTO** [comment]
@Figim Had one more report regarding this behavior. Currently we can't reproduce it but we are looking into it.

**Comment by xephos1one** [comment]
I can't play any YouTube video at all anymore.
This morning before the plugin update everything was fine.

Grayjay Version 336
YouTube Plugin Version 285
There's no app update available in the Play Store. Is there an ETA?
There also was no notification to update the app.

Logs if needed:
7b2c59df-9bfb-48b9-bca8-bac1f5c77389

**Comment by Zvonimir-FUTO** [comment]
@xephos1one Google is reviewing the update. Once the review process is done you will be able to update.

**Comment by Figim** [comment]
> [@Figim](https://github.com/Figim) Had one more report regarding this behavior. Currently we can't reproduce it but we are looking into it.

Could it be related to the following? 

![Image](https://github.com/user-attachments/assets/6d8c5b2b-79da-44e5-b6c6-17b1c18195f0)

Pr: https://github.com/FreeTubeApp/FreeTube/pull/7887

**Comment by Zvonimir-FUTO** [comment]
@Figim we already wait for backoff when protocol tells us to but we will continue investigating tomorrow.

**Comment by Figim** [comment]
> [@Figim](https://github.com/Figim) we already wait for backoff when protocol tells us to but we will continue investigating tomorrow.

Ok! 
I didn't update the plugin just now. Videos still not playing

**Comment by IronGibbet** [comment]
Hi,
I'm here from [2728](https://github.com/futo-org/grayjay-android/issues/2728)
I updated (sorry for that, update checks were disabled) yet still the same behavior.
I got a new toast though, something about failing to decline google consent (sorry the toast dissappeared to fast) so in order "trying new cypher" --> "fallback to visualized ..." --> google consent decline failed --> neither comments nor video load (the video not loading further than 0:59 seconds is similar but comments load in that instance.
Thanks in advance IG.

**Comment by exaltotun** [comment]
I also updated to version 285 of the youtube plugin today and haven't been able to get youtube to play since

**Comment by orhan98** [comment]
Make sure you are on the latest Grayjay app version as well, for android you can download it from here: https://grayjay.app/#download

**Comment by NormanMises** [comment]
What’s going on? The video was playing fine before the update, but it doesn’t work anymore after the update

**Comment by Zvonimir-FUTO** [comment]
> What’s going on? The video was playing fine before the update, but it doesn’t work anymore after the update

It's to early to say but we have few theories. In any case we are investigating it.

**Comment by breadPANbao** [comment]
> > What’s going on? The video was playing fine before the update, but it doesn’t work anymore after the update
> 
> It's to early to say but we have few theories. In any case we are investigating it.

Just wanted to say thanks to you and the team for working on these bugs! 🫡

**Comment by SignalRaptor** [comment]
Not sure if you guys have been able to reproduce the issue yet or if you've gotten details on how it's not working, feel free to hide this if it's irrelevant. 
Upon attempting to play a YouTube video, the video will not load, displaying a time code of “0:00 / -12:-55” and the play/pause buttons rendered over each other. Everything else such as description, comments, likes, and live chat still load as expected.
Upon receiving the update, I was told I needed to log in to YouTube, which I found odd since I was already logged in. I logged out and back in, no change in behavior but the message informing me that I had to went away. 
Downloads fail with either “no valid video source” or “failed initial stream request”. This happens 99% of the time on my home network, however (and this may be coincidental) consistently after I get to my job and connect to the corporate Wi-Fi, that rate drops to about 50%. Or it used to, since the update nothing has worked 100% of the time and I'm only able to watch previously downloaded content.
I'm on Android release 337 with yt plugin 285

**Comment by Zvonimir-FUTO** [comment]
Please update to 286 and report back. 
If you are on Play Store version you will have to wait for the review to be done for the Grayjay release.

**Comment by Keyaku** [comment]
> Please update to 286 and report back. If you are on Play Store version you will have to wait for the review to be done for the Grayjay release.

I was waiting for this comment:
I have both the app updated to 337 and the plugin updated to 285 (I'm using the FUTO repo, so I think I'm always up-to-date) and, currently, playback of videos is hit and miss. It either plays or doesn't play a video; when it doesn't, it's stuck with a frame with 0:00/-12:-55 on the timer.

YouTube plugin version 286 isn't available at the moment.

I'd also like to note, probably not news for the team, that 720p playback is visibly heavily compressed and lower quality, and options 1080p and up are now missing from videos that had them. YouTube most likely managed to restrict Premium quality streams somehow. Kind of a bummer, but this might be debatably justified and push for people to buy their Premium subscription; which I stopped doing given the insane idea that downloaded videos require an internet connection to make sure a subscription is valid (and that ads would _still_ show up).

Once again, I haven't touched the options other than "Fallback with Player Script" which was asked in this discussion.

I'll keep testing throughout the day to see if anything changes.

Thank you for your efforts so far!

**Comment by Figim** [comment]
> Please update to 286 and report back. If you are on Play Store version you will have to wait for the review to be done for the Grayjay release.

Thank you! It worked great. 🙂

**Comment by flexxyfluxx** [comment]
Can also report that 286 seems to work. Have now been able to play multiple videos without issue.

**Comment by Zvonimir-FUTO** [comment]
@Keyaku 286 should be available. Please check again.

**Comment by Keyaku** [comment]
> Keyaku 286 should be available. Please check again.

I was updating my comment right this moment; had to reinstall due to signatures mismatch.

So far, it looks it's working, particularly **with** the options 1080p and up. If anything happens, I'll report back.

If necessary, you may close this issue and I'll file a new issue.

Thank you for the hard work!

**Comment by Zvonimir-FUTO** [comment]
Closing as resolved.

**Comment by Zvonimir-FUTO** [comment]
Apologies for bump but wanted to inform you that desktop version 10 has been released so should work there.

**Comment by Patapom** [comment]
Hi, I'm the reporter for bug [2733](https://github.com/futo-org/grayjay-android/issues/2733) that was closed as duplicate of this one and I'm afraid to report the issue is still there with version 286...

**Comment by Figim** [comment]
@Kelvin-FUTO Sometimes when uploading a video, the error "Video could not be uploaded", "i.reverse is not a function" appears 

![Image](https://github.com/user-attachments/assets/a96f43a1-f057-41f1-ba04-263a064a10b3)

![Image](https://github.com/user-attachments/assets/039aee94-4f8e-4df4-b93c-e2ad5540a530)

**Comment by cypheir** [comment]
I am getting the following messages when I attempt to load a YouTube video:

1. Falling back to virtualized player. (x2)
2. Using YTSession Client
3. YTSessionClient got pot [MnamH]

Then an error popup appears woth the description: 
"Failed to load video
Promise failed: I.reverse is not a function"
With the options:
- Close
- Retry

One more process message appears at the bottom behind the popup:

4. YTSessionClient got pot [Mnbbv]

**Comment by Keyaku** [comment]
It's best to follow the new issue #2747 since this problem sounds sufficiently different from the ones in this thread.

**Comment by Zvonimir-FUTO** [comment]
As @Keyaku mentioned, "Promise failed" issue will be resolved through #2747 

@Patapom from the #2733 you were still on 336 version of Grayjay. Did you update to the latest?
If you are still encountering issue maybe it would be best to open a new bug report or comment inside #2733 so we are not notifying 20+ people in the thread.

**Comment by octagonalsquare** [comment]
This is happening again to me on GJ v17 with YT plugin v335. I set my logging level to debug but the log.txt file has only 2 lines in it about creating new threadpools and nothing else.

If there’s a new version of GJ, how can I force an update, as it isn’t prompting me?

**Comment by Zvonimir-FUTO** [comment]
> This is happening again to me on GJ v17 with YT plugin v335. I set my logging level to debug but the log.txt file has only 2 lines in it about creating new threadpools and nothing else.
> 
> If there’s a new version of GJ, how can I force an update, as it isn’t prompting me?

This should've been fixed through https://github.com/futo-org/grayjay-android/issues/3233

**Comment by octagonalsquare** [comment]
> This should've been fixed through [#3233](https://github.com/futo-org/grayjay-android/issues/3233)

It stopped later that day without any changes or reboots or anything. But I’ve had it happen off and on for a while. Also, how can I get logs? As described in my comment, setting a high log level doesn’t seem to change what is put in log.txt and no matter what, it seems to only have two lines with nothing useful.

**Comment by Zvonimir-FUTO** [comment]
> > This should've been fixed through [#3233](https://github.com/futo-org/grayjay-android/issues/3233)
> 
> It stopped later that day without any changes or reboots or anything. But I’ve had it happen off and on for a while. Also, how can I get logs? As described in my comment, setting a high log level doesn’t seem to change what is put in log.txt and no matter what, it seems to only have two lines with nothing useful.

It was fixed on our remote resolver so no plugin update was needed. This was changed recently to improve cipher issue handling.
As for the logs, unfortunately other logs can only be extracted from logcat or plugin development board.

**Comment by octagonalsquare** [comment]
> It was fixed on our remote resolver so no plugin update was needed. This was changed recently to improve cipher issue handling. As for the logs, unfortunately other logs can only be extracted from logcat or plugin development board.

I realize now that I misread your comment. Thanks for fixing it so quick!

Maybe that can be a feature request to add a better way to export logs. It would be really good for normal users to have a way to provide their logs when we run into users
