### ISSUE TITLE
Bug: UMP videos won't start

### ISSUE THREAD

**Issue by SdoggaMan** [futo-org/grayjay-android#2787]
### Reproduction steps

When letting a video sit for a while, and it needs to re-buffer/load to resume playback, the video performs the 'Grayjay loading process' (3 blue wheels) and sometimes loads comments, then immediately displays the following as an in-app toast briefly (including on PiP): 

"Failed to load UMP, no stream data. 
Try restarting plugin/app. 
47:10, 46:142, 35:15" 

<img width="1220" height="1067" alt="Image" src="https://github.com/user-attachments/assets/0ee05aeb-e5a8-460d-9e7d-9f2eef139e75" />

### Actual result

The video shows the timestamp as -12:-55 and the play/pause icons are overlaid on each other. No other player HUD appears and the video does not load. Restarting and clearing the app cache do not help; it seems like a random amount of time helps but I have only had this happen to me twice; once in a podcast video and once in a recent stream VOD. Playback in both cases were between 60-60 minutes, and hours later. I have not yet been able to try a logout/in or a phone restart and this has only started since the most recent update (from I think Friday or perhaps Thursday.)

As far as I can see it's always those numbers. I didn't know Grayjay was Christian! (Kidding, of course. I have no idea if 47:10 is a passage and if it is I have no idea what it says. "John 47:10; and he said, do not load that which the subject wisheth not to watcheth in his heart, for his content is dry, and his life meaningless... Eth.")

### Expected result

Video playback should resume where it left off (or I should be able to find the video and resume, either at 0:00 or using the "resume playback" option.) If UMP failed, it should retry or fallback; the app should not go into an non-functioning state/should be recoverable. 

If I can provide anything more to help please let me know!

### Grayjay Version

340

### What plugins are you seeing the problem on?

YouTube

### Plugin Version

290

### Which android version are you using?

15

### Which device are you using?

Moto Edge 60 Pro

### Which operating system are you using?

Android

### When do you experience the issue?

- [x] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

Yes

### References

Potentially #2784 or #2762 

### Relevant log output

```shell

```

**Comment by SdoggaMan** [comment]
I've just discovered that it will play another video fine while still having this issue with another. I went to go back to a podcast video after watching a few shorter ones just now and that podcast is throwing the error, but I've just finished watching other content.

**Comment by Zvonimir-FUTO** [comment]
Could you share your Youtube plugin settings?

**Comment by SdoggaMan** [comment]
For sure! The only thing lost here is the reinstall option. Hope this is what you need? I also submitted logs but I never got a toast/notif to give you the ID or anything. Will share again now though in case it didn't work. 

<img width="1220" height="14188" alt="Image" src="https://github.com/user-attachments/assets/6e463030-f09c-4b05-9516-2e475d1499ca" />

**Comment by SdoggaMan** [comment]
Also for what it's worth; some videos seem to be completely locked off for now (for example; last WAN show vod, the Distractible podcast eposide called "Dippy Dawg Does Dunkirk") but I've just watched the most recent William Osman video, and here's it playing a GN video. I tried to keep playing the WAN show vod on Saturday and Sunday and still wasn't happy. Weird...

<img width="1220" height="2712" alt="Image" src="https://github.com/user-attachments/assets/676e724c-95e0-4661-b3ab-03921c7a10a3" />
<img width="1220" height="2712" alt="Image" src="https://github.com/user-attachments/assets/b24fb43f-bafb-4966-ab82-55bb9547711e" />

**Comment by Zvonimir-FUTO** [comment]
Thanks for the screenshots. 

Could you check which streams fail for you? Just open video resolution settings and you should see either `IOS` or `UMP` next to resolution.

Could you also test with **Use Login for video details** disabled?

**Comment by SdoggaMan** [comment]
Definitely all UMP, I remember checking - here's another example on the most recent TechLinked video: 

<img width="1220" height="4615" alt="Image" src="https://github.com/user-attachments/assets/29998f3f-d6f8-4f5e-bae2-1b3e944ebc93" />

And I'll test that setting off tonight and let you know asap!

**Comment by SdoggaMan** [comment]
Same video - I got some DVD-TV-esque "Waiting for media to become available" loading screen and the video played. Weeeeird! Good catch!

I'm guessing that gives you an idea of where to go next?

**Comment by Zvonimir-FUTO** [comment]
What you experienced was a backoff. Youtube tries to force you to watch ad first.
Could test some more today and give us feedback on it? 

Use login for video details is mostly needed for some age restricted videos and membership content and if you have **Allow loginfallback** enabled than it's going to fallback automatically so you probably don't need this enabled.

If it is the case that this causes the issue then we have to look into it.

**Comment by SdoggaMan** [comment]
Definitely can man, of course!

I assume if I turned it on (I don't remember screwing around in the source settings but it's definitely possible I did to try to resolve other, since-squashed bugs in the past) then it's been that way for a while, and likely not getting in the way of much age-restricted stuff. Tell me, does the youtube account having age verification of it's own (the old-school stuff that lets you watch sensitive content, not this new government ID BS) effectively mean all age-restricted videos should play? Or is there an intermediate step of some kind that Grayjay needs (in this setting) as well? 

Anyway will test away and let you know if anything else changes on this one for sure!

**Comment by Zvonimir-FUTO** [comment]
If you are have a Youtube account and your age is over 18 you should be able to watch age restricted videos.
In Grayjay, we have an option inside Youtube plugin settings to Allow age restricted videos which you already enabled. This is optional and if disabled, Grayjay won't play age restricted videos.

**Comment by SdoggaMan** [comment]
But it'll still play them _if the account itself can,_ right? I'm generally asking out of my own curiosity at this point more than anything else!

So far, two videos that didn't play before are working (the news video, the podcast) with the "DVD loading screen" and all. Definitely not definitive but a positive movement! Will keep you updated!

**Comment by Zvonimir-FUTO** [comment]
Yes, if you the account is not Youtube Kids account and age is over 18, Grayjay will play the video.

**Comment by SdoggaMan** [comment]
Kool! Cheers for the help on this one and hopefully I can return the favour with help on the bug. It does seem like it's to do with that setting so far, so let's see what happens! Let me know if there's more you need from me. 😁

**Comment by Zvonimir-FUTO** [comment]
When Use login for video details is enabled, do all videos stop working all only some of them? In case it's only for some videos, could you link the examples?

What would you say the reproduction rate is from 1 out of 10?

**Comment by SdoggaMan** [comment]
Oh, on enabling, I now see the warning - might be useful to also have this beneath the toggle too. Anyway, turning back on, the same videos stop working. Here's 3 examples that don't load for me, although two of them DID load at one point: 

https://www.youtube.com/watch?v=k7nIcJE943c (Never been able to watch this on Grayjay)
https://www.youtube.com/watch?v=YVHXYqMPyzc (Started watching on Grayjay, bugged out at some point roughly 2/3 through)
https://www.youtube.com/watch?v=mlP9bXnLPZ8 (< Definitely went to sleep with this in the queue, it's "fully watched" in Grayjay)
(Don't hate me for watching LTT content on a Rossmann-affiliated app please 😜)

**Comment by Zvonimir-FUTO** [comment]
and all the other videos work?

**Comment by SdoggaMan** [comment]
Sorry I realise I didn't fully answer you. 

I'd say reproduction rate WAS sporadic for a bit; I'm certain I got the WAN show to resume for a bit there, but now it's 100% not working. Turning the toggle OFF works and turning back ON breaks it. It's definitely 'not going to play'. OTHER video does work, so it's almost like it's some backwards reaction to the setting; maybe YouTube is now flagging whatever that switch does as a block, when before it would spoof being age appropriate? 

For reference, these videos worked fine: 
https://www.youtube.com/watch?v=EaXJ1rQ2v5k
https://www.youtube.com/watch?v=3L2YiSGcNQM

Took a sec to load on a black screen but that's more or less normal. They're playing now.

**Comment by SdoggaMan** [comment]
> and all the other videos work?

Definitely not all other videos; chucked on the most recent Rossmann video and it's borked too. Above works first try though!

**Comment by Zvonimir-FUTO** [comment]
and the videos that work are not iOS streams?

**Comment by Zvonimir-FUTO** [comment]
Also does reopening the app help? (while option still enabled)

**Comment by Zvonimir-FUTO** [comment]
another thing that comes to mind... Can you play these videos on regular Youtube (browser/app) while logged in?

**Comment by SdoggaMan** [comment]
FriendlyJordies video is ploaying UMP 1080p30, no other options. Ethan video at UMP 720p30, same deal, no iOS option. I've never been able to find the option to even _allow_ iOS before (I've heard it loads quicker than other options which is one area the YT ap just creams Grayjay for me) so I'm not sure if I'm missing something there. I think I've had iOS options before... 

Sorry I'm a nuthead when it comes to remembering stuff I haven' specifically had to remember, so I'm sort of re-relearing this as you ask!

> Also does reopening the app help? (while option still enabled)

Nope. I've reopened, cleared cache, and restarted the phone; only thing I haven't done is log out and back in.

**Comment by SdoggaMan** [comment]
> another thing that comes to mind... Can you play these videos on regular Youtube (browser/app) while logged in?

Yep! I've been falling back to the YouTube app to play them there A-OK. (Please, god, get me out of here, it's so bloated, oh god, oh please. Please god.)

**Comment by Zvonimir-FUTO** [comment]
Could you try logging out and back in?

**Comment by SdoggaMan** [comment]
> Could you try logging out and back in?

With clear or without?

**Comment by Zvonimir-FUTO** [comment]
With clear.

**Comment by SdoggaMan** [comment]
Done, logged out with clear, video has loaded as normal. Arguably faster than it did? 
All three examples are okay following that!

**Comment by Zvonimir-FUTO** [comment]
Glad to hear that. It seems it was something session based. Unfortunately these examples are super hard to figure out unless it occurs for us.

Will close the issue as resolved for now. Thank you for all the testing.

**Comment by SdoggaMan** [comment]
Not to reopen this per se, but just thought I'd let you know that it regressed (with that setting on) at some point today, and the video I had playing at the end of yesterday/overnight wouldn't play today. I think it was like that this morning so _something_ about leaving a video/Grayjay sitting there "loaded" so to speak, and having to fetch media again(?) causes this, it seems. Works fine with the setting off. 
Thanks again for helping!

**Comment by blackletum** [comment]
Same exact issue, but on a pixel 7 and not logged in (never have been). Same versions otherwise as OP. cleared cache as suggested elsewhere but bug persists.

**Comment by RyanKet** [comment]
I'm having the same issue too, but it looks like it's because YouTube itself is down right now.

**Comment by NicholasFlamy** [comment]
I'll add a same to the other guys.

**Comment by MiniMic6** [comment]
same issue but mine only had 46:142 and a Script exception error as shown in the images below 

<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/36b18ddf-ab69-49ec-b243-90a31354a9ea" />

<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/1621302c-1df5-4ef8-972a-ee90f464880f" />

also log output 
3b52074a-25ce-4d07-a86a-96f03561f6f9

**Comment by RyanKet** [comment]
> same issue but mine only had 46:142 and a Script exception error as shown in the images below
> 
> <img alt="Image" width="1080" height="2000" src="https://private-user-images.githubusercontent.com/154101513/501761033-36b18ddf-ab69-49ec-b243-90a31354a9ea.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA1NzMzNzYsIm5iZiI6MTc2MDU3MzA3NiwicGF0aCI6Ii8xNTQxMDE1MTMvNTAxNzYxMDMzLTM2YjE4ZGRmLWFiNjktNDllYy1iMjQzLTkwYTMxMzU0YTllYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAxNlQwMDA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGI1NTIyMGMwNWE2NGJmOTU1ZWJjZGRmYzY4N2Q4YzhiNjc2ZmJiOTBmNmJhMzgzNjA4ZGI3MGU5MzI1MzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cPufoyW48SA0iW0lqZV2tRAdHr8MI66IXoq4x3M7KOg"> <img alt="Image" width="1080" height="2000" src="https://private-user-images.githubusercontent.com/154101513/501761060-1621302c-1df5-4ef8-972a-ee90f464880f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA1NzMzNzYsIm5iZiI6MTc2MDU3MzA3NiwicGF0aCI6Ii8xNTQxMDE1MTMvNTAxNzYxMDYwLTE2MjEzMDJjLTFkZjUtNGVmOC05NzJhLWVlOTBmNDY0ODgwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAxNlQwMDA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDJhMTM4NTkxNmRiZmJjMDRjMmU5Mjc0NzMxMDI0ZDE4NGY2Y2JjNWJmNzhiYTY4ZTllZTJjNGYyYjU0ZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cDeU379ZFsl-FGTb00rrBflijfWfU6HJGI_P9jVe1Fw">

YouTube itself is down right now, so that might be the reason why.

**Comment by MiniMic6** [comment]
> > same issue but mine only had 46:142 and a Script exception error as shown in the images below
> > <img alt="Image" width="1080" height="2000" src="https://private-user-images.githubusercontent.com/154101513/501761033-36b18ddf-ab69-49ec-b243-90a31354a9ea.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA1NzMzNzYsIm5iZiI6MTc2MDU3MzA3NiwicGF0aCI6Ii8xNTQxMDE1MTMvNTAxNzYxMDMzLTM2YjE4ZGRmLWFiNjktNDllYy1iMjQzLTkwYTMxMzU0YTllYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAxNlQwMDA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGI1NTIyMGMwNWE2NGJmOTU1ZWJjZGRmYzY4N2Q4YzhiNjc2ZmJiOTBmNmJhMzgzNjA4ZGI3MGU5MzI1MzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cPufoyW48SA0iW0lqZV2tRAdHr8MI66IXoq4x3M7KOg"> <img alt="Image" width="1080" height="2000" src="https://private-user-images.githubusercontent.com/154101513/501761060-1621302c-1df5-4ef8-972a-ee90f464880f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA1NzMzNzYsIm5iZiI6MTc2MDU3MzA3NiwicGF0aCI6Ii8xNTQxMDE1MTMvNTAxNzYxMDYwLTE2MjEzMDJjLTFkZjUtNGVmOC05NzJhLWVlOTBmNDY0ODgwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAxNlQwMDA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDJhMTM4NTkxNmRiZmJjMDRjMmU5Mjc0NzMxMDI0ZDE4NGY2Y2JjNWJmNzhiYTY4ZTllZTJjNGYyYjU0ZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cDeU379ZFsl-FGTb00rrBflijfWfU6HJGI_P9jVe1Fw">
> 
> YouTube itself is down right now, so that might be the reason why.

oh yeah maybe lmao, it would explain why newpipe fails too, though youtube's ads still work for some reason

<img width="1410" height="881" alt="Image" src="https://github.com/user-attachments/assets/00997fff-3a9f-404b-aa77-68fd2695d3d4" />

**Comment by SdoggaMan** [comment]
Oh shit wait is THAT why my YouTube music isn't working? See _this_ is why we all hate streaming services, say it with me now...

Anyway it's interesting to see that others are having the same issue!

**Comment by MiniMic6** [comment]
ok youtube itself seems back up I do apologize for intruding this thread

**Comment by Friend739** [comment]
This started happening today with every video I try to play. Same message... Failed to load UMP, no stream data.
Try restarting plugin/app.
47:10, 46:142, 35:15

Edit: aaaand it works fine now. I made no changes to settings. Weird

Edit 2: it's happening again. 🤷

**Comment by dimyself** [comment]
I started getting this a few days ago. Yesterday and today have been really bad. This happens on most videos, and I have to cycle IP's (including no vpn) , kill and restart grayjay, and then sometimes videos will load.

I also turned off the youtube source setting "Use HTML5 LIvestreams instead of IOS". This seems like it may have helped some, but only sometimes. No videos were loading for me. Then after turning this off, videos started loading again sometimes. Louis Rossmann's latest video still won't load for me though (and at random times, many others don't either).

I also found that once videos stop loading with this loading screen... no matter how many videos I try, the same thing happens. Then when I kill and open grayjay again, sometimes it will start working again (but not always)

I took a screen recording of the loading with errors: 

https://github.com/user-attachments/assets/bd44480f-afa9-4711-93c1-da5d2063e292

**Comment by Figim** [comment]
YT is experimental and may or may not require something. It may not require UMP sometimes or may require another codec. So playback fails

Or maybe it's related to Recàptcha. Grayjay sometimes has to pass Recàptcha. There are ways to do this automatically.

**Comment by SdoggaMan** [comment]
For whatever it's worth, I turned that setting back on perhaps a week or two after this whole thread I was originally involved in, and it hasn't happened to me since. Maybe it's something on individual accounts (like age verification, recaptcha or similar) or something with how Grayjay parses the feed? 

It's still on; will report back if it reoccurs (esp. now that others are starting to get it too!)

**Comment by Figim** [comment]
> For whatever it's worth, I turned that setting back on perhaps a week or two after this whole thread I was originally involved in, and it hasn't happened to me since. Maybe it's something on individual accounts (like age verification, recaptcha or similar) or something with how Grayjay parses the feed?
> 
> It's still on; will report back if it reoccurs (esp. now that others are starting to get it too!)

Try this. 

https://github.com/user-attachments/assets/6080c2a3-1d05-4acb-886a-f35bff00a49f

**Comment by dimyself** [comment]
> YT is experimental and may or may not require something. It may not require UMP sometimes or may require another codec. So playback fails
> 
> Or maybe it's related to Recàptcha. Grayjay sometimes has to pass Recàptcha. There are ways to do this automatically.

How can I do captchas automatically?

Youtube hardly asks for them...

But rumble is bad now, it pops up multiple times per video load and multiple times per feed refresh

**Comment by dimyself** [comment]
> For whatever it's worth, I turned that setting back on perhaps a week or two after this whole thread I was originally involved in, and it hasn't happened to me since. Maybe it's something on individual accounts (like age verification, recaptcha or similar) or something with how Grayjay parses the feed?
> 
> It's still on; will report back if it reoccurs (esp. now that others are starting to get it too!)

What setting are you referring to?

**Comment by dimyself** [comment]
> I started getting this a few days ago. Yesterday and today have been really bad. This happens on most videos, and I have to cycle IP's (including no vpn) , kill and restart grayjay, and then sometimes videos will load.
> 
> I also turned off the youtube source setting "Use HTML5 LIvestreams instead of IOS". This seems like it may have helped some, but only sometimes. No videos were loading for me. Then after turning this off, videos started loading again sometimes. Louis Rossmann's latest video still won't load for me though (and at random times, many others don't either).
> 
> I also found that once videos stop loading with this loading screen... no matter how many videos I try, the same thing happens. Then when I kill and open grayjay again, sometimes it will start working again (but not always)
> 
> I took a screen recording of the loading with errors:
> 
>  efQdIGS.-.Imgur.mp4

Ok, so i turned off "Force UMP Streams", just to try it... and videos are loading right away now

Is this setting needed?

I've only tried a few videos since turning it off, so i'm not sure it is working yet

***UPDATE **

Yeah, it looks like turning off force UMP streams is working for me (so far). All videos are loading again without any issues again

Not only are they all loading  again,  but they are loading faster with this setting off also.

**Comment by dimyself** [comment]
> > I started getting this a few days ago. Yesterday and today have been really bad. This happens on most videos, and I have to cycle IP's (including no vpn) , kill and restart grayjay, and then sometimes videos will load.
> > I also turned off the youtube source setting "Use HTML5 LIvestreams instead of IOS". This seems like it may have helped some, but only sometimes. No videos were loading for me. Then after turning this off, videos started loading again sometimes. Louis Rossmann's latest video still won't load for me though (and at random times, many others don't either).
> > I also found that once videos stop loading with this loading screen... no matter how many videos I try, the same thing happens. Then when I kill and open grayjay again, sometimes it will start working again (but not always)
> > I took a screen recording of the loading with errors:
> > efQdIGS.-.Imgur.mp4
> 
> Ok, so i turned off "Force UMP Streams", just to try it... and videos are loading right away now
> 
> Is this setting needed?
> 
> I've only tried a few videos since turning it off, so i'm not sure it is working yet
> 
> ***UPDATE **
> 
> Yeah, it looks like turning off force UMP streams is working for me (so far). All videos are loading again without any issues again
> 
> Not only are they all loading again, but they are loading faster with this setting off also.

I havent had this issue a single time today since turning this off. It seems to have fixed it for me

I'm not sure if this setting is needed or not though.

**Comment by Zvonimir-FUTO** [comment]
@dimyself Force UMP streams is not needed and off by default. It's mostly used for testing when you specifically want UMP streams.

You are now using Android streams which work for you.

**Comment by dimyself** [comment]
> [@dimyself](https://github.com/dimyself) Force UMP streams is not needed and off by default. It's mostly used for testing when you specifically want UMP streams.
> 
> You are now using Android streams which work for you.

Yes thank you. It is still working well for me after turning it off

I also noticed that the 5 second blue wait / loading screen is gone with this setting off. Videos load quicker with it off as well. 

Thank you

**Comment by Figim** [comment]
@Zvonimir-FUTO  I updated to the latest version of Grayjay today and this fixed it (Partially) 

It still happens in some videos

**Comment by Figim** [comment]
@Zvonimir-FUTO  "Use Combined UMP" works better. 
**Note: Android and iOS streams are disabled. "UMP forced" is used.** 
 
But it doesn't play videos 14 hours+. Maybe some adjustments are needed. (If I turn on the webm audio and video options in Grayjay settings, all videos work normally). This happened once when I played a 4-hour video.(less than 14 hours). But the second time I played it, there was no problem.

https://github.com/user-attachments/assets/be7129dd-10f7-44c2-88e3-9e3e071a558f

**14 hours+ Video playback with Webm audio and video options** 

https://github.com/user-attachments/assets/02834c9b-808c-4cc3-be10-47031b059653

**Comment by Figim** [comment]
Now nothing helps. Video playback is not possible with UMP

**Comment by Zvonimir-FUTO** [comment]
> Now nothing helps. Video playback is not possible with UMP

Could you update to the latest version of Grayjay and see if it's fixed?

**Comment by Figim** [comment]
> > Now nothing helps. Video playback is not possible with UMP
> 
> Could you update to the latest version of Grayjay and see if it's fixed?

**I have now updated the app. Plugin version 309. 14 hours+ videos are frozen at -12.55** **MP4**

"Use Combined UMP" 

Note: Android and iOS streams are disabled. "UMP forced" is used.

https://github.com/user-attachments/assets/5f17f611-61e1-4aaa-9cb4-311f35e466b0

**When you open the Webm video and audio options, all videos are played. Maybe YT requires this by default? You have to set it to automatic? Because when I play a video on YT, it plays opus for audio and vp9 for video. **

https://github.com/user-attachments/assets/cca878a7-d465-4788-9dd5-39978fddcefe

**Comment by Zvonimir-FUTO** [comment]
@Figim there is a separate issue opened for that issue https://github.com/futo-org/grayjay-android/issues/2827

Closing this one for now.

Desktop needs new update to support combined UMP.
