### ISSUE TITLE
Bug: Video Stutter

### ISSUE THREAD

**Issue by Allvaldrsson** [futo-org/grayjay-android#2961]
### Reproduction steps

0. Play a YouTube video that offers 60 FPS.

### Actual result

Video playback stutters at random. Stuttering intervals vary from a few seconds to non-stop. No buffering issues. No interruptions of the audio. The issue only affects visuals and also occurrs after downloading the video. Exporting the video and opening with VLC yielded stutter-free playback.

### Expected result

Smooth playback.

### Grayjay Version

355

### What plugins are you seeing the problem on?

YouTube

### Plugin Version

305

### Which android version are you using?

Android 16

### Which device are you using?

Google Pixel 6a

### Which operating system are you using?

Stock Android

### When do you experience the issue?

- [x] While logged in
- [ ] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell

```

**Comment by Zvonimir-FUTO** [comment]
Could you screenshot the quality settings of the video that stutters?
Does this happen for every video? How reproducible is it for you?

Does it happen on smaller resolutions as well?

**Comment by Allvaldrsson** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/88a2bdac-837e-4e4d-ab4c-9b33b54ebb65" />


Stuttering doesn't happen every single video but it does happen with noticeable frequency. It's occurred on videos with a lot happening on screen and some with just an individual on camera speaking, and it's happened in both landscape/fullscreen and portrait angles.

My preferred quality was set to 1080p. I've been able to duplicate the issue on multiple videos that use "Android 1080p60 video/mp4, avc1.64002a". Changing quality settings to one lower _or_ higher seems to resolve the stuttering. 

I will continue testing with different default quality settings to see how the behavior changes.

**Comment by Allvaldrsson** [comment]
I've been repeating the same offending video over with different default quality settings, from 2160p60 down to 360p30. The stuttering only occurs when using the "Android 1080p60 video/mp4, avc1.64002a" quality setting. If I begin video playback in a different quality and try switching to 1080p60, stuttering seems to occur after 40 to 60 seconds of playback following the setting change. Changing quality settings again to something other than 1080p60 removes the stuttering and no instance occurs even after several minutes of playback. Note, the YouTube plugin version was automatically updated from 305 to 308. 

P.S. I've further been able to duplicate the 1080p issue using different videos.

**Comment by JoelColby** [comment]
This began happening to me this afternoon immediately after updating to Android 16 on my Pixel 7 Pro. Like the original poster, this is only happening for videos when the quality is 1080p60.

**Grayjay Version:** 355
**YouTube Plugin Version:** 309
**Android Version:** Android 16
**Device:** Google Pixel 7 Pro
**Operating System:** Stock Android 16
**Logged In/Out:** Logged Out
**Using a VPN?:** No

I had a video in my Downloads on Grayjay prior to updating to Android 16 that I had started and not finished. After resuming this video following the Android upgrade, the video begins to stutter randomly (it's almost like the framerate drops -- the playback speed seems consistent). Initially, I thought the video was corrupted, but if I seek back to the part that stuttered, playback would resume normally, and some time later it would stutter at another random point in the video.

I enabled verbose logging, closed the app completely, resumed the downloaded video, and played through until I experienced a stutter. I submitted the log and was provided the following UUID, if it helps with troubleshooting: `06aded8f-41e5-4540-b42e-a75339cbe2e3`

**Comment by tcreek** [comment]
It happens to me sometimes. Rebooting the device usually resolves it

**Comment by mmoduu** [comment]
I have this problem too. Interestingly it only happens with 1080p60 resolution. If I use for example 2160p60 it does not stutter. 1080p60 resolution version on the example video I used for testing (https://www.youtube.com/watch?v=lt5yh5lTI7Q) is avc1.64002a but 2160p60 is vp9. Also, interestingly this problem started after upgrading to Android 16. Could it be upstream issue after all?

Google Pixel 8 Pro
GrapheneOS 2025121201 (Android 16)
Grayjay 355, Youtube 309

**Comment by Figim** [comment]
Maybe it's a media3 problem?

**Comment by Aultus-defora** [comment]
It seems that using webpm fixes the 1080p issue. Mp4 video is what stutters

**Comment by myxxmikeyxx** [comment]
I am having this issue, I'll have to try the webpm thing. I am also getting this issue on videos I download and play as well. #2995 is what I made. Probably will get closed but I just found this but wasn't any of the terms I used to search for existing just got lucky finding it.

**Comment by myxxmikeyxx** [comment]
I have found so far something that might be a "fix". I still need to test it more but it looks like disabling picture in picture mode has fixed the video dropping to lower framerate and having to pause and play to get it back to normal. I have not tried downloading a video and doing play back but it seems to be working for regular video streaming.

**Comment by BenMorgenstern** [comment]
I have had this issue happening with 100% reproducibility for a couple weeks now.

It's worst when at 720p60, after a few seconds of normal playback the FPS drops down to very low levels. The video isn't buffering and audio is fine. Switching the playback to 1080p60 is a little better, but the video still stutters some. Any higher or lower than those two options and the video runs smoothly.

Stuttering only seems to happen for YouTube videos. Twitch streams do not have the issue.

Pausing and playing temporarily fixes the stuttering, but it returns after a few seconds. 

I'm using a Pixel 9a on Android 16. Issue started happening right around the time I upgraded from Android 15 to 16.

**Comment by Brian5647** [comment]
> I have found so far something that might be a "fix". I still need to test it more but it looks like disabling picture in picture mode has fixed the video dropping to lower framerate and having to pause and play to get it back to normal. I have not tried downloading a video and doing play back but it seems to be working for regular video streaming.

I tried your "fix" but sadly thia does not fix the problem for me while watching a video

**Comment by Zvonimir-FUTO** [comment]
Maybe you guys can try enabling **Force UMP Streams** in Youtube plugin settings since it doesn't happen on UMP streams. At least until we fix the issue.

**Comment by DevilzAvacado** [comment]
> Maybe you guys can try enabling **Force UMP Streams** in Youtube plugin settings since it doesn't happen on UMP streams. At least until we fix the issue.

Just found this thread about this issue. I'm still getting dropped frames with forced ump streams. Not only on gj but on other youtube apps. I'm on pixel 9a with GrapheneOS.

**Comment by Zvonimir-FUTO** [comment]
> > Maybe you guys can try enabling **Force UMP Streams** in Youtube plugin settings since it doesn't happen on UMP streams. At least until we fix the issue.
> 
> Just found this thread about this issue. I'm still getting dropped frames with forced ump streams. Not only on gj but on other youtube apps. I'm on pixel 9a with GrapheneOS.

Interesting that you get it with UMP streams as well. And thank you for the feedback because we are suspecting the issue is in Exoplayer and the fact that it is happening in other apps makes sense in that case.

**Comment by Zvonimir-FUTO** [comment]
Think this was fixed in OS update, are you guys still encountering this?

**Comment by BenMorgenstern** [comment]
I'm still having the issue with the latest Android 16. Takes about ~30s before the frames start to drop.

**Comment by Zvonimir-FUTO** [comment]
> I'm still having the issue with the latest Android 16. Takes about ~30s before the frames start to drop.

Did you update your system recently? Are you on stock or GrapheneOS?
After the latest update on GrapheneOS the issue is no longer present on my device.

**Comment by BenMorgenstern** [comment]
> Did you update your system recently? Are you on stock or GrapheneOS? After the latest update on GrapheneOS the issue is no longer present on my device.

I'm just on stock Android 16

**Comment by Zvonimir-FUTO** [comment]
@BenMorgenstern if you go to system settings > About phone, what is your build number?

**Comment by BenMorgenstern** [comment]
@Zvonimir-FUTO BP4A.260105.004.E1

**Comment by Zvonimir-FUTO** [comment]
Seems that was released on 12.01.2026. while my GrapheneOS build is dated to last week. 
What is your Kernel version? Press on Android version from About phone page.

**Comment by BenMorgenstern** [comment]
Kernel Version:
6.1.145-android14-11-gc1de4747ac59-ab14219743
#1 Mon Oct  6 16:50:48 UTC 2025

**Comment by Zvonimir-FUTO** [comment]
Yeah, I'm on 6.1.161.
Closing this since the issue appears to be on the OS side. Please check again after update is released for stock.

**Comment by Zvonimir-FUTO** [comment]
Let me reopen it since I keep seeing the same issue again. I guess the bug is in Exoplayer.

**Comment by myxxmikeyxx** [comment]
I am still having this issue as well. if i use webm it works fine but not everyone uploads that.

**Comment by BenMorgenstern** [comment]
Just following up to say this issue seems to have finally resolved itself for me.

Still on Android 16 with the same kernel version mentioned above. My build number is now BP4A.260205.001.

**Comment by Doc-4** [comment]
Still getting this, latest Grayjay/GrapheneOS/Pixel 8 Pro. UMP streams are what's offered to me, android is enabled and UMP force disabled, but I only see UMP. Stutter's as bad as ever, fairly frequent. FWIW I've seen this in PipePipe too.

**Comment by Blockguy24** [comment]
I'm getting this even when on "Android" video sources, video stuttering every few seconds, but for some reason restarting the app can (temporarily?) fix the stuttering. (Pixel 8, stock operating system)

**Comment by Doc-4** [comment]
VP9 seems to work better. I suggest trying to use those streams when available. But yeah, the bug definitely still exists.

**Comment by Doc-4** [comment]
This seems to have improved lately even on AVC, currently using android streams. Haven't noticed stuttering.

**Comment by D0t-Matrix** [comment]
I'm also seeing this issue on my Pixel 9 Pro running GrapheneOS. It _appears_ to only occur on videos with 1080p60 or higher quality, and going down to 720p60 has resolved this issue every time I've encountered it. It has **_definitely_** improved with the last couple of plugin versions, as a few weeks ago the video stuttering was also resulting in the audio periodically pausing & skipping ahead to catch up.

Google Pixel 9 Pro
GrapheneOS 2026032001 (Android 16)
Grayjay 372, Youtube 335

**Comment by pxe1833** [comment]
Still a consistent issue, even with Android video format.

Example: https://www.youtube.com/watch?v=IHItbgHutVo @ 1080p/60fps

OS: Stock Android
Model: Pixel 7
Build: CP1A.260305.018
Grayjay @ 372, YouTube plugin @ 335

**Comment by SCBionicle** [comment]
I noticed a pattern that might be related to the root cause. On Pixel devices, watching YouTube videos in Grayjay seems to hit the CPU particularly hard, causing the phone to heat up significantly. Once the phone gets hot, thermal throttling kicks in and stuttering begins. While the stuttering via heat throttling affects all apps, Grayjay's playback seems to get hit the worst.

​Interestingly, I don't see this same heat/stuttering issue with other providers in Grayjay. My theory is that this specific stuttering is tied to thermal throttling caused by how the YouTube plugin is handling playback (which might explain why users above are seeing differences between AVC and VP9 streams).

​This could likely be confirmed by profiling the CPU load and thermals via ADB with Grayjay in debug mode.

**Comment by Doc-4** [comment]
I agree with the above analysis, but I don't think the cause in my case is always thermal throttling. My pixel 8 pro doesn't really seem to heat up all that much, at least not noticeably more than it used to. I'm not intimately familiar with how grayjay or the plugin handle video decoding, but I think the problem might have something to do with how decoding itself is handled, like decoding is suddenly bottlenecked arbitrarily.

I'm able to reproduce bad results reliably on certain types of videos. If anyone would like logs collected, let me know how you'd like logcat run.

**Comment by SCBionicle** [comment]
@Doc-4 We have the same type of phone, Pixel 8 Pro. I'm on the stock OS.

Just so it's easier to analyze the discrepancy between us, do you use a protective case with your phone? If you do, what is its thickness and material?

I'm using a thinner case that is magsafe and general wireless charging compatible with a magnetic/metallic ring to clamp to wireless chargers.

**Comment by Doc-4** [comment]
Mine's similar to yours, magsafe case that's protective but not super bulky. I can still feel the device heat up on heavy workloads.

**Comment by SCBionicle** [comment]
I have a script that monitors my battery temperature, mine gets to 102 °F during playback of Midwest Safety member videos. Non-member videos will still tax my phone, but it won't get quite as hot. 

That script starts warning me when my batt temp gets to 107 degrees. Unfortunately, I cannot directly measure my CPU temperature as the system doesn't seem to broadcast that information, at least in a way that I know how to access in a non-rooted phone.

**Comment by SCBionicle** [comment]
Weird thing, and I don't know if this is related, but I actually ran into this in the native YouTube app today too. I had switched over to it thinking it would be more stable, but I noticed the exact same stuttering observation I’ve been seeing here.
​Checked 'Stats for Nerds' (screenshot attached) and I’m dropping ~12% of frames (752/6148) on a Pixel 8 Pro. This is on an av01 4K60 stream with a 52s readahead, so it’s definitely not a bandwidth issue.
​It makes me wonder if YouTube is poisoning all streams that might seem third party and made their algorithm so sensitive that it flags their own clients as well. If Grayjay has successfully mimicked their request patterns, YouTube might just be catching everyone in the crossfire.

[Youtube Source Video](https://youtu.be/l4I7RR1Xxpo?si=iIAWnXNOwEaEmo6v)
<img width="1344" height="2992" alt="Image" src="https://github.com/user-attachments/assets/ca7d030e-dbfd-495b-ad6b-973e548c28f6" />

**Comment by SCBionicle** [comment]
Adding a bit more context on how to reproduce this: I've noticed this stuttering strongly correlates with my Grayjay usage volume, particularly when it fails on member-only videos.
Crucially, I believe this throttling is tied to the Account Level, not the IP or session. The stuttering behavior follows me across different locations/networks and is completely device and app agnostic. If I hit an authentication wall on a member video in Grayjay, and then switch over to the native YouTube client (even on a different network), my account continues to be served these 'dirty', frame-dropping AV1 streams.
It heavily implies that YouTube's backend is assigning a persistent, account-bound QoS penalty based on third-party request patterns, effectively catching their own native clients in the crossfire if the user switches apps.

**Comment by SCBionicle** [comment]
Okay, I've been doing some light black-box testing to narrow this down.

I tried watching Grayjay on my Surface Book 2 and did not notice the service degradation. However, hardware decoding on Intel and Nvidia chips is much more mature and resilient to "poisoned" or malformed streams, whereas mobile decoders on Snapdragon and Tensor are highly optimized but brittle. Because an x86_64 desktop-class processor has significantly more processing headroom than a mobile SoC, the playback engine brute-forces through the bad stream, making the throttling much harder to notice.

On Grayjay Android, I turned on Incognito mode and watched an hour-long video for about 10 minutes. I did not run into the stutter at all (and verified it was unauthenticated by checking that the video was not added to my YouTube history).

This strongly indicates that the tracking is account-level, rather than session-level or device fingerprinting (especially taking into account that the native YouTube app on the same device still stutters when logged in).

I hypothesize that YouTube is doing heuristic network pattern tracking on clients to detect 3rd-party apps, using a reputation metric to flag specific accounts. Previously, the stutter penalty would only last for about a day before disappearing if I went back to the native app. Now, I've been getting a consistent stutter on this account for more than 3 weeks.

If YouTube is pouring resources into this cat-and-mouse game, it is very possible they have specifically whitelisted FUTO's known developer accounts and IPs. If that's the case, the FUTO team might never naturally encounter this "poisoned" stream behavior, which would explain the difficulty in reproducing it.

Unfortunately, I do not have dedicated debugging tools or reverse engineering tools installed on either of my two devices to capture diagnostic data. While I might be willing to assist with this reverse engineering, I'm on some rather intensive side projects of my own, so my time will be limited. Regardless, feel free to reach out if you think I could be of assistance.

**Comment by SCBionicle** [comment]
Below is the video I tested incognito mode on.

https://www.youtube.com/watch?v=_VTH9mLX8y8

**Comment by SCBionicle** [comment]
I hope this helps.

**Comment by Zvonimir-FUTO** [comment]
We pretty much boiled it down to ExoPlayer. We have exported the video and played it with ExoPlayer which had stutter while with gstream it didn't. We tried updating the exoplayer to newer version but that didn't help.

However switching to a new video player is a big task and could cause a lot of new issues in the process. This is something we are considering in future.

**Comment by Doc-4** [comment]
I also suspected the problem had something to do with exoplayer since I've seen similar issues in other apps that use it. I'm curious, did you see that the issues were uniform across all devices and SoCs, or that some interact worse than others?

**Comment by SCBionicle** [comment]
Migrating to a video player framework that better handles nonstandard streams is definitely something worth considering and may help mitigate the present issue. However, if my hypothesis is correct, even slightly, that will only help for a limited amount of time.

Considering the other issues on this repository revolving around YouTube, I think at least some degree of aggressive adversarial development is definitely at play at YouTube's service level. Even if YouTube is being adversarial, I don't think circumventing YouTube's detection and punitive suite is insurmountable, but it will require serious and careful consideration regarding architectural moves going forward.

**Comment by Zvonimir-FUTO** [comment]
> I also suspected the problem had something to do with exoplayer since I've seen similar issues in other apps that use it. I'm curious, did you see that the issues were uniform across all devices and SoCs, or that some interact worse than others?

From all the users in this thread it appears to be only happening on Google Pixel devices, regardless of OS being stock or Graphene.

**Comment by phuyc** [comment]
> From all the users in this thread it appears to be only happening on Google Pixel devices, regardless of OS being stock or Graphene.

Seems like that is the case. I had no problem before with my old phone, but now it's stuttering on my new Google pixel phone.

**Comment by TRUEtennisfan** [comment]
Also experiencing video lag on my Pixel 9.

**Comment by wombatpandaa** [comment]
Just wanted to hop on and add my experience to the pile. Refurbished Pixel 9 on GrapheneOS here, having the stuttering issue. On average probably once a minute but that's a vibes-based guess. Happy to provide diagnostics if desired.

**Comment by lbueker** [comment]
I am experience this issue now basically on all videos after the recent update to android 17 using graphene os on a pixel 10 pro xl.

**Comment by Doc-4** [comment]
@lbueker In the quality/format section, switch to WebM from MP4. There's probably something wrong with the H264 decoding in exoplayer, if I had to guess.

**Comment by Zvonimir-FUTO** [comment]
Fixed in v391, however, you will have to enable **Native UMP Player** in advanced settings of Youtube plugin. Please provide us with feedback if issue is truly gone :)

**Comment by lbueker** [comment]
Works great for me.

**Comment by SCBionicle** [comment]
The stutter is largely receded for me but not fully gone. It is a major improvement over what it is before, however, the stutter I was suffering was when Grayjay was using Android source over UMP. I'll try to find a UMP video and let you know.

**Comment by Zvonimir-FUTO** [comment]
> The stutter is largely receded for me but not fully gone. It is a major improvement over what it is before, however, the stutter I was suffering was when Grayjay was using Android source over UMP. I'll try to find a UMP video and let you know.

You can enable Force UMP in Youtube settings to always get UMP. Also can you confirm you enabled Native UMP player?

**Comment by JoelColby** [comment]
For me, this is still happening when watching videos with: **Android VR 1080p60 video/mp4 avc1.64002a**. This happens when streaming the video and also when downloading the video and watching it after the download is completed.

This does not happen when adjusting the video quality down to: **Android VR 720p60 video/mp4 avc1.640020**

I have enabled Native UMP Player in the advanced settings. I don't have Force UMP enabled in the YouTube settings though.

**Comment by Figim** [comment]
New versions of Android VR and Android client now require UMP. If UMP is not forced, there will be problems. (But not for everyone)

**Comment by Doc-4** [comment]
Is the new native UMP a replacement for or an augmentation to the Android VR/iOS streams? I'd thought UMP was its own way of streaming. I'd forced UMP assuming that it was necessary to test the new implementation. (which seems to work pretty well so far)

**Comment by SCBionicle** [comment]
> > The stutter is largely receded for me but not fully gone. It is a major improvement over what it is before, however, the stutter I was suffering was when Grayjay was using Android source over UMP. I'll try to find a UMP video and let you know.
> 
> You can enable Force UMP in Youtube settings to always get UMP. Also can you confirm you enabled Native UMP player?

I have native UMP enabled but I don't have it forced. Will test and let you know.

**Comment by Zvonimir-FUTO** [comment]
> New versions of Android VR and Android client now require UMP. If UMP is not forced, there will be problems. (But not for everyone)

This is wrong, Android and AndroidVR are separate streams for those clients, UMP is different protocol completely.

**Comment by Figim** [comment]
> > New versions of Android VR and Android client now require UMP. If UMP is not forced, there will be problems. (But not for everyone)
> 
> This is wrong, Android and AndroidVR are separate streams for those clients, UMP is different protocol completely.

I'm not saying that. It's already like that. It's just that not all countries are affected. 

https://github.com/MorpheApp/morphe-patches/pull/2094

**Comment by JoelColby** [comment]
I did some additional testing with Native UMP Player in the advanced settings and Force UMP enabled in the YouTube source settings.

Stuttering also occurs when playing back a downloaded 1080p60 UMP video with the H264 codec. When streaming UMP videos, all of the video quality options have the VP9 codec, which do not seem to have this issue.

Using the same video, testing both streaming it (if the option is available for that quality/codec) and also downloading it first and then playing it back:
- **Android VR 1080p60 video/mp4 avc1.64002a (Native UMP Player, no forced UMP in YT)** - Video stutters after 60-90 seconds of playback
- **Android VR 1080p60 video/mp4 VP9 (Native UMP Player, no forced UMP in YT)** - No stuttering
- **UMP 1080p60 video/mp4 H264 (Native UMP Player, forced UMP in YT)** - Video stutters after 60-90 seconds of playback
- **UMP 1080p60 video/mp4 VP9 (Native UMP Player, forced UMP in YT)** - No stuttering

For all 4 videos, I also exported the video from Grayjay and played it back in the Android VLC app. All 4 videos play without stuttering when using VLC.

**Comment by SCBionicle** [comment]
I think the native UMP player seems to have solved the stuttering in UMP streams on my end, at least with videos streamed in the VP9 codec. Unfortunately, loading the video in UMP sometimes results in GrayJay hanging in a possible deadlock resulting in GrayJay panicking after a few minutes and exiting with a fatal error describing an async timeout exception. I'll try to capture it the next time it happens. I have reported the error through the app's native crash report system.

**Comment by Zvonimir-FUTO** [comment]
@SCBionicle could you tell us around which time and which date did you submit the logs?

**Comment by SCBionicle** [comment]
I can't. The only thing I remember is that my last crash happened yesterday and it seemed to be another issue and the last time I let the deadlock timeout was within the last 5 days but GrayJay errored on sending the error report saying the connection to the server timed out. 

When it happens again, I will post here.

**Comment by Zvonimir-FUTO** [comment]
Please do, also when you submit the crash, crash ID will be copied to your clipboard and you can paste it here so we can easily find it :)

**Comment by Doc-4** [comment]
I did notice the current version of forcing UMP along with the new native setting doesn't seem to work with currently running live streams, though it might have just been temperamental in the moment. I haven't noticed the stuttering since, though I haven't been trying to force it to come out either

**Comment by Zvonimir-FUTO** [comment]
@Doc-4 What do you mean it doesn't seem to work with currently running live streams? Can you open a separate issue for this?

**Comment by Doc-4** [comment]
@Zvonimir-FUTO 
#3408

**Comment by HeNeugier** [comment]
Same issue for me. Identical symptoms on Pixel 8 Pro running GrapheneOS.

**Comment by HeNeugier** [comment]
Now getting stuttering on long videos with the VisionOS 720p60 mp4 preset (avc1.640020) in addition to the 1080p preset (avc1.64002a)
GrayJay: v391
Youtube: v358
GrapheneOS: 2026081301

**Comment by Qxji** [comment]
I am also getting stuttering on grapheneos on speeds faster than 1x. On 720p and 1080p. Does not seem to occur on 480p

youtube is v364 

grayjay v391

**Comment by Doc-4** [comment]
I noticed the stuttering shows up when using a non-UMP stream that's mp4 and not webm, and is worse the larger the resolution. For now I force UMP.
