### ISSUE TITLE
End of video is cut off

### ISSUE THREAD

**Issue by GoodDays13** [futo-org/grayjay-android#36]
This doesn't matter too much for most videos, but some videos have some sort of joke or cut-off thing like a cut scream right before the video ends. In the app, the video seems to stop a tiny bit before the video actually ends cutting off like half a second. here are 2 videos I've noticed this messes with:
https://www.youtube.com/watch?v=5y1f01kPSVo
https://www.youtube.com/watch?v=qpBKTGBCN0Y

**Comment by JustCryen** [comment]
Yup, basically every video is affected by this but the one that made me finally check if it's already been reported was this one.
https://youtu.be/itQLBGQyTX8&t=1563

**Comment by carloslockward** [comment]
I have noticed this too

**Comment by Bluscream** [comment]
Happens to me aswell. I'm really curious on what is causing this. @koen-futo could you chime in on this potentially?

**Comment by koen-futo** [comment]
@Bluscream I have done some initial investigation but it doesn't look like a quick fix. ExoPlayer tells us the time bar for the video. For now it has less priority due to other higher priority issues.

**Comment by Bluscream** [comment]
> @Bluscream I have done some initial investigation but it doesn't look like a quick fix. ExoPlayer tells us the time bar for the video. For now it has less priority due to other higher priority issues.

what happens if you just take exo's reported length+1s ? i would much rather have 1 second of blackscreen than 1 second missing at the end

**Comment by koen-futo** [comment]
That might work as a hackfix, ideally we spend some time figuring out the root cause and making a proper fix.

**Comment by Bluscream** [comment]
Well, you can provide this as a quick workaround, and take the meantime to properly and thouroughly find a real fix :brain:

**Comment by jextrevor** [comment]
Also seeing this issue with all YouTube videos. I don't see the issue happening with Odysee videos

**Comment by jarredpickles87** [comment]
Still seeing videos getting cut off by about a second. Just wanted to update the report.

**Comment by cesarila** [comment]
Yep, same. It's especially noticeable on the "Trackmania 2020 World Records" channel, since they end their videos promptly at the finish line of the world record comparison.

**Comment by Doc-4** [comment]
Still getting this, even on Louis's channel. Hope this gets fixed soon

**Comment by FragileAgile** [comment]
Have had this happening to me for a while now, finally mustered up the will to write a bug report but seems it's been happening to others, no change so far

**Comment by Philippe-Choquette** [comment]
I was like:
_Huh. MKBHD doesn't say "Peace" at the end of his videos anymore._

**Comment by Titaniumtown** [comment]
> I was like _Huh. MKBHD doesn't say "Peace" at the end of his videos anymore._

haha i forgot he said that since using grayjay lol

**Comment by Bluscream** [comment]
Missed opportunity to name the issue "End of video is cut o"

**Comment by RehmatSChawla** [comment]
I've seen this too, in almost every video I watch to the end I notice the last bit of the sentence being cut off.

**Comment by DerangedWifi** [comment]
Sorry, not sure if this is a dead issue, but Im having this issue on the latest version of grag for all videos. Yr plugin V205, Grayjay 264, Android Note 9.

**Comment by skylarmt** [comment]
Still happening, really annoying.  I've had to open NewPipe for a couple videos that have the joke at the end.

Fairphone 5, CalyxOS 5.12.1, Android 14

**Comment by jakecornet** [comment]
This issue is still happening, but I think I can offer some more info.  This happens to me whenever I cast YouTube to a TV, as well.  It's definitely an issue on YouTube's end, but I still hope there's a workaround as mentioned earlier in this thread.  Perfectly cut videos are some of my favorite.

**Comment by Doc-4** [comment]
It's a little misleading to call this an issue with YouTube considering both first-party and third-party clients don't consistently have it. It's definitely still there, but you guys fixed the line bug. I believe in you to fix this one too, last thing keeping me from defaulting to Grayjay

**Comment by Zvonimir-FUTO** [comment]
Related comment https://github.com/futo-org/Grayjay.Desktop/issues/210#issuecomment-2566806763

**Comment by Zvonimir-FUTO** [comment]
This should be fixed in the latest version. Ping me to reopen if you are still affected.

**Comment by Doc-4** [comment]
Yeah, it's definitely better, but not gone

**Comment by Zvonimir-FUTO** [comment]
Wonder if this is only on iOS streams. Will have to come back once we fix UMP streams again.

**Comment by JustCryen** [comment]
Well, If I remember correctly it was here from the beginning.  Prior to the UMP block.

**Comment by Zvonimir-FUTO** [comment]
Seems to only affect iOS streams. We will investigate this.

**Comment by SdoggaMan** [comment]
I've had this too, for the entirety of my Grayjay usage it feels like, on every video - just to a differing extent. It _feels_ to me like the player is taking the video length and rounding to the nearest whole second; so, for example, a video of length 10:32:89 gets shortened by 89% of a second to 10:32:00. This results in anywhere from the last fraction of a word, to several short words being cut off. This might not _actually_ be what's happening but that's the best way I can describe the feeling of inconsistent endings. Of course it could just always be a full second short but depends on how much time the content creator left between their final word and the literal end of the video. It does _not_ feel like it's only one type of stream, but it's possible that it is and I simply don't notice when the end of a UMP stream is present vs. an iOS stream cuts off. One of those 'only notice it when it's bad' problems.

**Comment by skylarmt** [comment]
Here's a video that's entirely cut off by this bug, it doesn't play at all and there's no sound: https://www.youtube.com/watch?v=9__-KDhHz7Q

Might be a good way to test if this bug is fixed.  The video is under 1 second long so if it plays at all the problem is solved.

**Comment by TheDeviantCrafter** [comment]
On the desktop app, the video skularmt linked creates an error popup. On Android, it just ends instantly.

![Image](https://github.com/user-attachments/assets/08e1d406-bc1c-4bf6-8e5c-12b214ad785b)

Desktop version 5, Android version 285, both using Youtube plugin version 241.

**Comment by jakecornet** [comment]
The cut-off issue appears to be fixed on the latest version!!  Hopefully it doesn't come back again.

**Comment by jakecornet** [comment]
Nope, did some more testing and it's much better, but the end of this video is still cut off:
https://www.youtube.com/watch?v=eB69Hjyy6uY 
It cut off the end while using IOS streams.  Also, the length of the video is displayed as 12 seconds on the thumbnail, but 11 seconds on the actual video.

**Comment by jakecornet** [comment]
Selecting "force experimental UMP streams" in youtube plugin setting seems to fix the issue for me.

**Comment by Doc-4** [comment]
This error was fixed in UMP a while back, or at least it's not noticeable to me. IOS has been broken for as long as I remember them being an option, I just switched UMP to default. I do think this should be higher priority than it currently is, though. It's not a problem with the extractor, downloads don't omit anything.

**Comment by SdoggaMan** [comment]
If this is fixed I owe a big, wet, sloppy kiss to whoever fixed it! Thank you!

**Comment by Doc-4** [comment]
As of just testing this today, UMP seems to work correctly, IOS still cuts the stream off.

**Comment by chriskeeble** [comment]
Sad to see this is still a thing after 2 years.

**Comment by jakecornet** [comment]
This is a problem with IOS streams.  Switching to experimental UMP streams is a good fix right now.  UMP streams are more stable than ever on mobile.  Go into your YT plugin settings and enable "force experimental UMP streams" to fix the end of the video being cut off.  Seems to work well on desktop, too.

UMP streams were broken for about a month recently, but as of a week or two ago, they are working great!  The devs have been very responsive on fixing these sorts of issues that are only caused by YT putting hurdles in their way.

**Comment by PhilC813** [comment]
Still problematic that the default setting is to use IOS streams, and that this hasn't been fixed for months. The FUTO team has done an amazing job at improving many things, but this issue should now be given priority.

**Comment by Doc-4** [comment]
I believe this is an important issue. It's unfortunate something like captions for example is currently broken, but I think the most core functionality of a video player, "playing the whole video without errors" is a fairly key feature.

I don't know if many of the backend changes done to mess up 3rd party clients target this one more than others, but stream playback seem to need fixing often while some other implementations survive several changes without updates.

I value the great work that's gone into a functional and modular app that aggregates all video sites in one place, but I feel that occasionally some things that should be seen as more important are not, or there are difficulties I don't understand.

**Comment by jakecornet** [comment]
The end of the video being cut off is a problem with the official YouTubeTV app on my TV, too, so I don't fault GrayJay for it.  YouTube actively adds features designed to make full playback of videos hard for apps like GrayJay, too, including adblock detection.  Ibthink that's why the YT plugin has so many problems while others like Rumble don't seem to.

**Comment by Doc-4** [comment]
I have both had third party clients and the official client on android that don't have this problem. Downloading using Grayjay or many other methods such as yt-dlp results in an output containing the full stream on the same videos that suffer the issue, so the issue doesn't live on YouTube's servers, or all methods would create an output suffering from the same problem.

**Comment by jakecornet** [comment]
Looking back at another issue I opened, this was fixed at one point, but it caused downloads to be very corrupted, so they reverted the changes.  I'm not sure why GrayJay has these problems when some apps like NewPipe don't other than the fact that GrayJay offers other features that those apps don't.

**Comment by unoukujou** [comment]
I want to say that I'm noticing the same exact problem. For me it happens only in grayjay. Last second is cut off for whatever reason.

**Comment by Zvonimir-FUTO** [comment]
This should finally be fixed with new Android streams in v297.

**Comment by maaaks** [comment]
Even after the update to v297, the end is cut off on this video: https://www.youtube.com/watch?v=Z_gL2h4BwYs

The "Enable Android Streams" option is on. Should I enable or disable something else?

**Comment by Doc-4** [comment]
I used a video that makes it very obvious if this is working or not, and I double checked in the settings menu that it was in fact using the new Android streams for said specific video. Issue definitely still exists from my testing, only UMP streams eliminate it.

@Zvonimir-FUTO

**Comment by Zvonimir-FUTO** [comment]
Fixed finally! Enjoy 🥳

**Comment by jakecornet** [comment]
Woohoo, it seems to be! 🎉 Thank you!

**Comment by Doc-4** [comment]
Yep, can report the same, well done! 🎆

**Comment by PhilC813** [comment]
Wow, time to pop some champaign!

**Comment by fonikz** [comment]
Version 340 says it's the latest version, yet this is not fixed for me. Has been a problem for a very long time.

**Comment by Doc-4** [comment]
> Version 340 says it's the latest version, yet this is not fixed for me. Has been a problem for a very long time.

Did you make sure you're using Android streams, and not iOS? UMP also works when it isn't having issues.

**Comment by Zvonimir-FUTO** [comment]
> Version 340 says it's the latest version, yet this is not fixed for me. Has been a problem for a very long time.

Could you open a separate issue for this so we are not sending notifications to 25 people in this thread? Please make sure you are on the latest version of Youtube as well and please screenshot your plugin settings as well.

**Comment by fonikz** [comment]
It's now fixed as of one or two days ago. GrayJay version 340, YouTube version 300.

Apologies for the notifications.
