### ISSUE TITLE
Failed to load next page Plugin [Youtube]

### ISSUE THREAD

**Issue by DUBDUBHUB** [futo-org/grayjay-android#517]
Android Device: **Samsung Galaxy A33 5G**

OS: **Android 13**

GrayJay version: **210**

YouTube plugin version: **157**

Odysee plugin version: **33**

So I have been getting this error message ever since yesterday whenever I try to refresh my home section or when I try to scroll down to see more video  recommendations in the home section every other section is fine tho 
![image](https://github.com/futo-org/grayjay-android/assets/150360681/e1d69560-8d8a-4e54-93d0-838e0c650ba4)

**Comment by tarmovannas90** [comment]
Up - same with samsung s23 ultra android 14

**Comment by muflihansari** [comment]
Same here. I am facing this issue too.

Android 13.
Latest version of app and plugin.

**Comment by tarmovannas90** [comment]
So i want to share how i fixed, logged out and logged in again
![Screenshot_20231219_203046_Grayjay](https://github.com/futo-org/grayjay-android/assets/154284057/a59c84cc-fee3-4f0a-ba15-e3b436d520ac)

**Comment by DUBDUBHUB** [comment]
@tarmovannas90  It worked thanks

**Comment by DUBDUBHUB** [comment]
I am still going to wait and see what the dev team has to say before closing the issue tho

**Comment by koen-futo** [comment]
@DUBDUBHUB Good that you didn't close it or I would not have seen it. We will make a better fix for this that does not require any manual actions.

**Comment by Kelvin-FUTO** [comment]
In the upcoming version (>=v217, YT v159) we added a fix for the (home) trending page cause issues for logged in accounts.
Trending page is shown as substitute of the home page if your YT account has home disabled entirely (eg. disabling YT history causes Youtube to no longer provide a home page).

If after updating to YT v159 you still get 500 for nextPage, re-open this issue, let us know, and ideally tell us more any particularities your YT account may have that helps us reproduce it. (As this is not an issue for everyone)

**Comment by DUBDUBHUB** [comment]
Thanks, @Kelvin-FUTO  and the Grayjay team you guys are great and I greatly appreciate the work that you guys are doing. So far I haven't encountered the problem again after the fix, but I will let you know if it ever reappears.
